### ISSUE TITLE
Rewrite docstrings in numpy syntax

### ISSUE THREAD

**Issue by parente** [jupyter/kernel_gateway#100]
From https://github.com/jupyter/enhancement-proposals/pull/12#issuecomment-184066113:

> I wish the docstrings across the codebase were documented according to our guidelines (which basically boil down to 'use the [numpy docstring standard]'(https://github.com/numpy/numpy/blob/master/doc/example.py)). The key point there is to describe parameters in function signatures (such as this one).

**Comment by parente** [comment]
@willingc If we use the numpy docstring format, will it cause a problem later if we want to generate API doc in Sphinx? Are the other jupyter projects using this syntax with a sphinx extension to parse it? (I've only ever used the `@param foo` or `:param foo:` formats in the past with Sphinx.)

**Comment by willingc** [comment]
@parente It shouldn't cause an issue. My recommendation would be to look at the JupyterHub source for docstring examples there. Doing a quick scan of the source here, I would start by convert the triple single quote docstrings to double quote docstrings.

On another note, would you like me to submit a PR with the basic Sphinx doc structure that we are using on most of the other projects?

**Comment by willingc** [comment]
@parente In case, you are curious. We use Napolean as a Sphinx extension to handle the docstrings. http://sphinxcontrib-napoleon.readthedocs.org/en/latest/

**Comment by parente** [comment]
OK. I'll check out Jupyter Hub's way of doing it.

> On another note, would you like me to submit a PR with the basic Sphinx doc structure that we are using on most of the other projects?

That'd be great! It'll give us a leg up on https://github.com/jupyter-incubator/kernel_gateway/issues/101. 

> We use Napolean as a Sphinx extension 

Perfect. Now I know what to target.

BTW, Is this information in the dev docs for Jupyter somewhere?  It would be handy if other would-be contributors to any of the Jupyter projects knew the rough guidelines. I see http://jupyter.readthedocs.org/en/latest/contrib_guide_docs.html but I don't see mention of the numpy docstring format.

**Comment by parente** [comment]
Going to keep this open to address the test docstrings as well.

**Comment by parente** [comment]
Test docstrings are all in. Closing.

**Comment by willingc** [comment]
Awesome!
