### ISSUE TITLE
Create Sphinx docs for ReadTheDocs deploy

### ISSUE THREAD

**Issue by parente** [jupyter/kernel_gateway#101]
From https://github.com/jupyter/enhancement-proposals/pull/12#issuecomment-184066113:

> I also think it would be better to eventually move the docs to the integrated ReadTheDocs deployment; the reason isn't that it doesn't fit in a single markdown file, but rather that eventually we want users to find a comprehensive and coherent set of docs on that site. If key pieces of the architecture only have standalone READMEs on github, it's harder for the users to get the whole project-wide picture.

**Comment by willingc** [comment]
Almost done with this. Still needed:

- [ ] Text for Changelog and summary of changes for v5.0

**Comment by parente** [comment]
v0.5.0 is still a bit out. We've been updating the changelog with a PR just before release. Is the goal to do it along the way now?

**Comment by willingc** [comment]
Ahh...thanks for clarifying. I thought this was already 5.0. In that case, when you do the blog post are you mentioning a release number. If so, if you create a tag for the release number (or bump to 0.4.x) then the Sphinx docs will build as that release number. Otherwise the docs will be tied to master (the future 0.5.0) until it is tagged and released.

**Comment by parente** [comment]
I think it's OK to live with master for the moment. All the existing stable branches / tags have the equivalent docs in the README. And the goal of the post is only to state that KG has left the incubator and describe what it is.

**Comment by willingc** [comment]
Perfect :sunny:

**Comment by willingc** [comment]
Should we go ahead and close this?

**Comment by parente** [comment]
I was going to take one more pass through the README and docs site to see if there are any glaring issues. If not, I'll close and we can fix anything with follow on PRs.

Thanks again @willingc for getting this bootstrapped so quickly!

**Comment by willingc** [comment]
My pleasure :D You have been very responsive which makes my job easier. I expect we will iterate with future PRs on this.

I'm still motivated to figure out the Travis issue too.

**Comment by parente** [comment]
@willingc I notice the edit on GitHub link on the readthedocs site is busted. It assumes the files are *.rst on github. Any way to fix?

**Comment by willingc** [comment]
@parente Good catch. After some sleuthing, I found this is an underlying bug in Sphinx. Its fix is in the 1.4 alpha release of Sphinx but has been backported to 1.3.6. I've opened a PR #127 to use Sphinx 1.3.6+. Seems to work correctly with the change.

**Comment by parente** [comment]
I've been referring to the docs myself a few times over the past week. I haven't hit any other issues. I'm going to close this as done. We can make improvements to the doc content and structure over time.

**Comment by willingc** [comment]
Great!
