### ISSUE TITLE
ActivityManager tuneup

### ISSUE THREAD

**Issue by parente** [jupyter/kernel_gateway#107]
* [x] Instantiate singleton in gatewayapp for consistency with all the other managers. Put it in the app settings and ref it from there, not via a module import.
* [x] No need for dummy_map. Just make the global defaults a dict.
* [x] `ignore` grows endlessly
* [x]  ~~Instead of checking kg_list_kernels everywhere that calls ActivityManager methods, just check it in the ActivityManager instance itself. (Easy once it gets instantiated in the gatewayapp and can get the settings.)~~
* [x] ~~Calls to the activity manager should probably happen *after* the action takes place in case it fails.~~

**Comment by Lull3rSkat3r** [comment]
In regards to `ignore` growing endlessly: That was implemented to prevent kernels coming back into the activity list, albeit a naive solution. You can see this problem when a kernel is shutdown and then a client disconnects. 

The easiest way I can see to solve this is when kernels are added/deleted to the list the `ActivityManager` syncs with the list of kernels in the `KernelManager`. If there is a kernel in the `ActivityManager` which is not in the `KernelManager` it should be removed.

**Comment by parente** [comment]
Yep. Understand why ignore exists. Just need to garbage collect it. Checking the kernel manager makes sense. Once the AcitivityManager is like the other managers and shared via settings / constructors, it'll be easy for one to ref the other.

**Comment by parente** [comment]
Paired with @Lull3rSkat3r on the last two items. We agreed to leave things alone for the time being.

> Instead of checking kg_list_kernels everywhere that calls ActivityManager methods, just check it in the ActivityManager instance itself. (Easy once it gets instantiated in the gatewayapp and can get the settings.)

Moving all the checking logic into the activity manager still creates a tight binding between the notebook API and activity tracking. Only a pub/sub bus would really disentangle the two, and that seems overkill for the moment.

> Calls to the activity manager should probably happen after the action takes place in case it fails.

After looking at the code again, we settled on the mantra that activity values should be updated when there's intent from a client or a kernel, regardless of whether the action actually completes or not. As it stands, we recognize that the `CONNECTIONS` count from clients to a kernel can get out of sync if errors occur. We intend to treat that value as approximate for the time being until we receive feedback from users on how all this metadata winds up getting used. For example, if all that needs to be known is whether one or more clients is connected, but not the exact count, the timestamps are enough assuming the clients are sending proper heartbeats.
