### ISSUE TITLE
start_channels and wait_for_ready when preseeding all kernels?

### ISSUE THREAD

**Issue by parente** [jupyter/kernel_gateway#112]
https://github.com/jupyter-incubator/kernel_gateway/blob/master/kernel_gateway/services/kernels/manager.py#L65

Is this start and wait exclusive to notebook-http mode? Taking out the code entirely breaks nearly all the notebook-http mode tests. Taking out the `if` only has no visible impact.

**Comment by Lull3rSkat3r** [comment]
It should. Technically the remainder of the function should be under the `if` as well. This [line](https://github.com/jupyter-incubator/kernel_gateway/blob/master/kernel_gateway/services/kernels/manager.py#L71) only makes sense in `notebook-http` mode.

**Comment by parente** [comment]
Yes. I noticed that line too. It's not a big problem given that no cell will typically have an annotation when not in HTTP mode. But it could still be a problem in some cases (e.g., notebook serving dual duty) and shows the leakiness of the two modes. In #103, we'll look at how these might be disentangled.

**Comment by parente** [comment]
I think we should attempt removing the `if` and initialize the channel in both `notebook-http` and `jupyter-websocket` modes. @nitind can you make this simple change and see if anything breaks in the test suite or some of the demos?

**Comment by nitind** [comment]
On it.

**Comment by nitind** [comment]
Code path only applies when a seed notebook is being used. I haven't seen any issues with the change in automated and manual tests.

**Comment by parente** [comment]
Go ahead with a PR then. The less if/else for the modes we have, the better off we are for #103
