### ISSUE TITLE
Image to represent Kernel Gateway.

### ISSUE THREAD

**Issue by Carreau** [jupyter/kernel_gateway#124]
@parente will publish a blog post on blog.jupyter.org. 

It would be nice to have an image that kind of represent the kernel gateway to put on top.
Or more generally a logo that can be reused on slides ETC...
Thought ?

**Comment by parente** [comment]
Do you mean a logo or a diagram of how it might get used?

**Comment by Carreau** [comment]
More logo-ish. Something to put in the background like for https://blog.jupyter.org/2016/02/16/jupyterdays-boston-2016/. 


But you've already published so it's fine! Thanks for the Blog post !

**Comment by parente** [comment]
Do we still want a logo? There's no UI at all in the KG so not sure where else it would be used. And the typical Jupyter logo probably covers talking about it on charts, etc.

**Comment by willingc** [comment]
@parente @Carreau Is this ready to close?

**Comment by parente** [comment]
My 2 cents: I don't think we need a special logo.
