### ISSUE TITLE
tmpkg anyone?

### ISSUE THREAD

**Issue by parente** [jupyter/kernel_gateway#125]
I wonder if we should stand up an open access pool of kernel gateways using tmpnb for the community to use. Something like https://tmpkg.org

Reasons:
- Gives the community a place to experiment with new kernel clients (e.g., of the last couple hours https://twitter.com/OpenAnalytics/status/707326388500570112)
- Takes load caused by these experiments off the try jupyter notebook cluster which is meant to be for users to try the notebook
- It might help generate new, interesting use cases

/cc @rgbkrk @minrk @jtyberg @tverbeke

**Comment by minrk** [comment]
That seems like a good idea. We could still run it on tmpnb.org/kernelgateway.

**Comment by rgbkrk** [comment]
Yeah, we'd end up keeping two separate redirectors (and pools underneath). :+1:

**Comment by parente** [comment]
I'm doing some cleaning. I think we can close this out as a "no", as in "no time", "no hardware" and "no interest" at this point.
