### ISSUE TITLE
Swagger spec at /api/spec.yml

### ISSUE THREAD

**Issue by parente** [jupyter/kernel_gateway#135]
Problem: https://github.com/jupyter/kernel_gateway/issues/96 introduced a new API. We've got nothing in the doc about it or otherwise. Also, #133 might introduce changes to `POST /api/kernels`.

* [x] Put our own swagger doc that starts from https://github.com/jupyter/notebook/blob/602b5c945d9fb2a9c8a21e65f7ab54be2578257f/notebook/services/api/api.yaml at `/api/spec.yml`. The notebook server already implements the handler https://github.com/jupyter/notebook/blob/master/notebook/services/api/handlers.py. We just have to enable it here and update the spec to match what the KG provides.
* [x] Include a pointer in the documentation in the `jupyter-websocket` section with a pointer to the rendered spec

**Comment by parente** [comment]
Make sure the optional Authorization headers are documented as part of this.

**Comment by rgbkrk** [comment]
Hoorah, happy about Swagger here.

**Comment by Lull3rSkat3r** [comment]
Will be fixed with PR #142
