### ISSUE TITLE
Find an open port in a range of ports

### ISSUE THREAD

**Issue by dockter-84** [jupyter/kernel_gateway#151]
In jupyter_core, there is an option to set `NotebookApp.port_retries` to specify how many ports to try "above" the initially specified port, `NotebookApp.port`, to find the first available open port.

https://github.com/jupyter/jupyter_core/blob/62af662a4b21fef6223ef04ff6d2f2e1cc536181/jupyter_core/tests/dotipython_empty/profile_default/ipython_notebook_config.py#L28

We would like a similar option for kernel_gateway to allow us to specify a starting port (`KernelGatewayApp.port`), and a number of ports "above" that port to try.   Perhaps the option `KernelGatewayApp.port_retries` to re-use the naming convention of NotebookApp.

**Comment by parente** [comment]
Thanks for opening this. It should be easy to port the logic from the notebook server here:

https://github.com/jupyter/notebook/blob/master/notebook/notebookapp.py#L980
