### ISSUE TITLE
SessionManager API change in notebook 4.2

### ISSUE THREAD

**Issue by parente** [jupyter/kernel_gateway#155]
We state in the setup.py that we're 4.0 and up compatible. But looks like something in notebook 4.2 changed that might be breaking us:

https://travis-ci.org/jupyter/kernel_gateway/builds/124508434

**Comment by parente** [comment]
https://github.com/jupyter/notebook/pull/1237 changed the session handler. We only override GET on that handler to guard against session listing if a flag is set, but it's the POST that's failing. Most likely, our session manager needs to be made forward compatible.

**Comment by parente** [comment]
Yea. Right here.

https://github.com/jupyter/notebook/pull/1237/files#diff-c17b8b3e48aa051099afe81741f6baf1R67

@minrk @blink1073 is the SessionManager interface considered a declared public interface that people can override? If so, passing the new `kernel_id` in 4.2.0 (https://github.com/jupyter/notebook/blob/4.2.0/notebook/services/sessions/handlers.py#L62) is an incompatible API change. If not, no worries: it's just a private thing that broke KG.

**Comment by blink1073** [comment]
I don't see the specific problem.  That is a feature addition, in that if the specified kernel is already running, you get a handle to the kernel.

**Comment by parente** [comment]
I mean SessionManager is one of those plug-points in Notebook server. You can configure Notebook to run with a custom SessionManager via the command line or config files:

https://github.com/jupyter/notebook/blob/master/notebook/notebookapp.py#L742

I'm wondering if the SessionManager class interface is considered public API as a result or not.

The fix here is easy. Update the KG SessionManager impl to match the new interface. I'm more worried about others who might be providing their own SessionManager.

**Comment by blink1073** [comment]
Ah, I see what you mean now.  Yes, this was a breaking API change.

**Comment by minrk** [comment]
@parente sorry about that, I didn't see that when I backported it to 4.2, which I maybe shouldn't have done. I think there's a good chance that you have the only custom SessionManager, since it's not exactly a well-documented API, but it is technically public.

**Comment by parente** [comment]
>  I think there's a good chance that you have the only custom SessionManager, since it's not exactly a well-documented API, but it is technically public.

I concur. No worries. It's definitely a non-obvious case of API change (i.e., adding an optional parameter breaks backward compatibility).

**Comment by blink1073** [comment]
Technically it could be made backwards compatible by using `inspect` or checking for the `TypeError`, do you think it would be worth it?

**Comment by parente** [comment]
Would have to go here, minimally:

https://github.com/jupyter/notebook/blob/master/notebook/services/sessions/handlers.py#L61

Not worth the trouble if KG is the only known provider of a custom SessionManager in existence. I backported the fix to the last two minor versions that declared notebook >=4.0,<5.0 compatibility and have the session manager implementation.
