### ISSUE TITLE
Pull request #152 into version 0.4.x

### ISSUE THREAD

**Issue by dockter-84** [jupyter/kernel_gateway#157]
Can you "retro-fit" or "backport" the change seen in  https://github.com/jupyter/kernel_gateway/pull/152 into the 0.4.x branch?

At the moment we are not able to move to a 0.5 version,  but we would like this feature in a minor revision of 0.4.

**Comment by parente** [comment]
Lucky day. I'm backporting #156 to 0.4.1 and 0.5.1 where we declared compatibility up to 5.0. Can put the retries in too.

**Comment by parente** [comment]
Cherry picked and made the releases on the respective branches with this requested change and #156 to account for notebook 4.2 breaking change.

Occurs to me that just doing the cherry pick locally, tagging, releasing, and pushing on the branches is what I've been doing when only a few folks were working on this. There's probably a more careful / formal way that I should be doing it via PRs in the future.

**Comment by parente** [comment]
Ref: https://github.com/jupyter/kernel_gateway/tree/0.4.1
