### ISSUE TITLE
# ResponseInfo GET ignored for some Kernels

### ISSUE THREAD

**Issue by gavrand** [jupyter/kernel_gateway#159]
Hi

I am using Apache Toree as Jupyter Kernel and ResponseInfo is being ignored for it. It is working perfectly with standard Python2 Kernel. #Get does work perfectly !

I guess it is due to "shortcut" is being used to produce response_code in /services/notebooks/handlers.py (line 199)
```python
response_future = self.execute_code(kernel_client, kernel_id, response_code)
```
instead of full packing for request_code (line 180) 
```python
request = json.dumps({
                'body' : parse_body(self.request),
                'args' : parse_args(self.request.query_arguments),
                'path' : self.path_kwargs,
                'headers' : headers_to_dict(self.request.headers)
```
and hence remote Apache Kernel (interacting via Jupyter protocol) might not be happy with it.
Again, it is from my limited knowledge and time spent. However Apache PySpark does not work:I

Thank you
Andrey

**Comment by parente** [comment]
Thanks for the report, @gavrand . Can you confirm which mode you're running the kernel gateway in, with jupyter websockets or notebook http? Basically, what's your run command for starting the kernel gateway?

**Comment by gavrand** [comment]
Hi Peter

Thank you for the prompt reply. It is indeed notebook-http. 
The run cmd is below

`
jupyter kernelgateway --KernelGatewayApp.api=notebook-http --KernelGatewayApp.ip=0.0.0.0 --KernelGatewayApp.seed_uri=./notebook.ipynb --KernelGatewayApp.default_kernel_name=PySpark
`

Thank you 
Andrey

**Comment by parente** [comment]
@Lull3rSkat3r mind taking a look at this?

**Comment by Lull3rSkat3r** [comment]
I'll check it out.

**Comment by Lull3rSkat3r** [comment]
@gavrand, are you running Apache Toree with the scala or python interpreter?

**Comment by gavrand** [comment]
Hi @Lull3rSkat3r. It is python interpreter. 

Again, #Get is working perfectly. It is only ResponseInfo where I am struggling and hence could not dump application/json :(.
If you want I could try scala one also.

Thank you
Andrey

**Comment by Lull3rSkat3r** [comment]
@gavrand, would it be possible to attach your notebook?

**Comment by gavrand** [comment]
Hi @Lull3rSkat3r 

I am afraid, I am unable to send it from work by compliance reasons.
But the example from the github /kernel_gateway/tests/resources/responses_2.ipynb
does not work with Apache Toree Kernel also (the simplest one # GET /json)

Andrey

**Comment by Lull3rSkat3r** [comment]
@gavrand, no worries. I will use the example notebook. Will post my results soon.

**Comment by Lull3rSkat3r** [comment]
So investigating this in more detail exposed a bug in the Toree Kernel. Essentially the PySpark interpreter in Toree is returning `print` messages as an execute result. The KG code currently expects the code to output the response info via a stream message. You can see this by running a code cell in Toree PySpark:

![pyspark bug](https://cloud.githubusercontent.com/assets/1383927/15402437/d2c19418-1db9-11e6-9371-9a5fc0bb07b8.gif)


This might bring up the point of reading the `text/plain` value from an execute result, but is not directly the fault of KG. If we do not want to support this we can close. I have opened a bug on Toree for the real issue [TOREE 318](https://issues.apache.org/jira/browse/TOREE-318).

**Comment by gavrand** [comment]
Thank you very much for investigation, Corey !

Andrey

**Comment by parente** [comment]
Tracing through the issue @Lull3rSkat3r noted above, it appears this problem has been fixed by https://github.com/apache/incubator-toree/pull/47.

Going to close here since the problem was in the dependency.
