### ISSUE TITLE
A pointer to the format of the configuration file 

### ISSUE THREAD

**Issue by dockter-84** [jupyter/kernel_gateway#166]
Although the command line options are nicely documented at http://jupyter-notebook.readthedocs.io/en/latest/config.html

The use of the options in a config file are vague.  That is:  what is the format of the file specified by `--KernelGatewayApp.config_file=<Unicode>`

According to @parente,  "Config system comes from notebook, and even they don’t have it fully spec’ed. they recommend running —generate-config and filling it in.  Open a defect and we can point over there at least."

**Comment by parente** [comment]
@minrk or @willingc Is there any other doc on the .py file config format that I might have missed?

**Comment by parente** [comment]
Found it: https://jupyter.readthedocs.io/en/latest/projects/config.html
