### ISSUE TITLE
Disposing Running Kernels by Ctrl_C in RHEL 

### ISSUE THREAD

**Issue by gavrand** [jupyter/kernel_gateway#167]
Hi 

Would be great if you could help me with the following problem.
I am running KernelGateway:

`jupyter kernelgateway --KernelGatewayApp.api='notebook-http' --KernelGatewayApp.ip=0.0.0.0 --KernelGatewayApp.port=8090 --KernelGatewayApp.seed_uri=<.ipynb> --KernelGatewayApp.max_kernels=1` 

against Spark Cluster.

When I am trying to kill the process with CTRL+C it dies successfully (I can't see jupyter-kernelg via ps -a). However, my kernel (Apache Toree) clearly is up and running. I could see the kernel in Spark UI among Running Applications.

I am wondering if it might be related to the following code in Gateway::start

`   try:
           self.io_loop.start()
        except KeyboardInterrupt:
            self.log.info("Interrupted...")
`

where does not seem to be any attempt to call shutdown and hence dispose existing kernel_pool.
Am I missing anything obvious ?

Thank you
Andrey

**Comment by parente** [comment]
The notebook server seems to suggest that the kernels should clean themselves up when their parent process dies:

https://github.com/jupyter/notebook/blob/master/notebook/notebookapp.py#L1151

It still sends an explicit shutdown request to cleanup connection files anyway:

https://github.com/jupyter/notebook/blob/master/notebook/notebookapp.py#L1251

The KG should probably dispose of the pool to cleanup connection files and make sure that kernels don't become orphaned.

It's interesting that Toree instances are left running, however. (cc @Lull3rSkat3r)

**Comment by gavrand** [comment]
Thank you, @parente for having a look.

I think there is no problem with Notebook. when I close a notebook via UI (Close and Halt) or Ctrl+C on jupyter notebook it indeed cleans everything perfectly. I see shutdown log msgs from Toree and the Kernel disappear from Running Applications list in Spark Cluster UI.
I guess it is happening precisely from this
https://github.com/jupyter/notebook/blob/master/notebook/notebookapp.py#L1251

and it is not what we have in KG at the moment. But again I am not an expert on KG <-> Notebook <-> Kernel interaction yet.

Thank you
Andrey

**Comment by parente** [comment]
I agree there is no problem with the notebook. I was wondering if there is a proble with toree. 

Regardless the explicit shutdown should be added to KG.

**Comment by Lull3rSkat3r** [comment]
@parente and @gavrand  we have two methods which could shutdown the kernels. One for the [KernelPool](https://github.com/jupyter/kernel_gateway/blob/master/kernel_gateway/services/kernels/pool.py#L29) class and one for the [ManagedKernelPool](https://github.com/jupyter/kernel_gateway/blob/master/kernel_gateway/services/kernels/pool.py#L154) class. Both methods get called from the `gatewayapp`'s [shutdown](https://github.com/jupyter/kernel_gateway/blob/master/kernel_gateway/gatewayapp.py#L486) method.

My guess is there is something different about our shutdown methods from the `KernelManager`'s one above. It is also peculiar that our shutdowns are not identical.

**Comment by gavrand** [comment]
Apologies for my ignorance, Corey - but would CTRL+C cause gatewayapp's shutdown method to be called ?
