### ISSUE TITLE
Unable to kill the subprocess of kernel_gateway

### ISSUE THREAD

**Issue by Engine-Treasure** [jupyter/kernel_gateway#181]
I have just got problem in kill the subprocess of jupyter kernel_gateway. There was no way I could find to kill the subprocess except killing the parent process first. I found that command **kill** had worked, but **Zombie** process was left. Then the parent process recreated the subprocess on the Zombie process.
```
[root@730dd8cc9235 etc]# ps aux
root         5  0.1  0.9 341912 37560 ?        Sl   15:29   0:02 /usr/local/python3.5/bin/python3.5 /usr/local/python3.5/bin/jupyter-kernelgateway --KernelGatewayApp.ip=0.0.0.0 --KernelGatewayApp.port=8889 
root        16  4.9  2.6 1030932 103472 ?      Ssl  15:29   1:02 /usr/local/python3.5/bin/python3.5 -m ipykernel -f /root/.local/share/jupyter/runtime/kernel-40b223ee-81f8-4812-af49-df7147d0d880.json
[root@730dd8cc9235 etc]# kill 16 && ps aux
root         5  0.1  0.9 341912 37560 ?        Sl   15:29   0:02 /usr/local/python3.5/bin/python3.5 /usr/local/python3.5/bin/jupyter-kernelgateway --KernelGatewayApp.ip=0.0.0.0 --KernelGatewayApp.port=8889
root        16  4.4  0.0      0     0 ?        Zsl  15:29   1:02 [python3.5] <defunct>
[root@730dd8cc9235 etc]# ps aux
root         5  0.1  0.9 341912 37616 ?        Sl   15:29   0:02 /usr/local/python3.5/bin/python3.5 /usr/local/python3.5/bin/jupyter-kernelgateway --KernelGatewayApp.ip=0.0.0.0 --KernelGatewayApp.port=8889
root        71 23.1  0.7 629544 28616 ?        Ssl  15:53   0:01 /usr/local/python3.5/bin/python3.5 -m ipykernel -f /root/.local/share/jupyter/runtime/kernel-40b223ee-81f8-4812-af49-df7147d0d880.json
```
As shown above, the subprocess was never killed. With the increase of the number of subprocess, the system resources are running out. With a huge number of users, isn't it badly terrible?
So is there any way to close the subrocess without killing the parent process?

**Comment by Engine-Treasure** [comment]
I run  the jupyter kernel_gateway manually in terminal. There is the result:

```
[root@730dd8cc9235 ~]# /usr/local/python3.5/bin/python3.5 /usr/local/python3.5/bin/jupyter-kernelgateway --KernelGatewayApp.ip=0.0.0.0 --KernelGatewayApp.port=8889 &
```
Then it got a request and spawned a subprocess. As I tried to kill the subprocess, it just restarted.

```
root@730dd8cc9235 ~]# ps aux
root        56  1.1  0.9 341876 37508 ?        Sl   16:50   0:02 /usr/local/python3.5/bin/python3.5 /usr/local/python3.5/bin/jupyter-kernelgateway --KernelGatewayApp.ip=0.0.0.0 --KernelGatewayApp.port=8889
root        88  0.1  0.7 629516 28596 ?        Ssl  16:53   0:00 /usr/local/python3.5/bin/python3.5 -m ipykernel -f /root/.local/share/jupyter/runtime/kernel-32d2a1e1-3bce-4d7c-b2e3-7205bf95e464.json
[root@730dd8cc9235 ~]# kill 88
[root@730dd8cc9235 ~]# [KernelGatewayApp] KernelRestarter: restarting kernel (1/5)
WARNING:root:kernel 32d2a1e1-3bce-4d7c-b2e3-7205bf95e464 restarted
```

**Comment by parente** [comment]
Are you running the kernel gateway in docker? If so, you need a proper init process like tini which we use over in the docker stacks project. Jupyter notebook / tornado, which KG is using under the covers, is not designed to be pid 0 on a system and so runs into oddities with dead or defunct children.

Also, if you want to shutdown a kernel cleanly without kill, you should send a HTTP DELETE to the API. Still, there's no guarantee without a proper init process that kernels deleted in this manner will be reaped properly either.

I can include some links about the docker issue when I'm not mobile. If you're not using docker, then please let me know. (I'm guessing from the generated  hostname in the prompted.)

**Comment by Engine-Treasure** [comment]
You guess right. And thank you for your suggestions~

**Comment by Engine-Treasure** [comment]
@parente 
Finally, I found that the restart was done by **Jupyter Notebook**, not **kernel_gateway**. It's nothing to do with **Zombie process**. The right way to shutdown the kernel is send a HTTP DELETE to the API (just what you said).
I'm sorry for my ignorance. Thank you again~
