### ISSUE TITLE
Is it possible to use the http mode from a notebook served via the jupyter notebook command?

### ISSUE THREAD

**Issue by rs2** [jupyter/kernel_gateway#185]
My use case: 
- Serve a notebook using the `jupyter notebook` command AND have some of its cells also available in http mode without separately executing jupyter kernelgateway`for the same`ipynb` file. 

Is that supported?

**Comment by Lull3rSkat3r** [comment]
@rs2, no that is currently not available. Trying to understand your use case more are you looking to test the notebook while developing it?

**Comment by parente** [comment]
I'm going to close this issue as inactive. If someone comes up with a nice pattern or extension for testing the http mode annotations in the notebook server itself, we can document it.
