### ISSUE TITLE
ERR jupyter_client.kernelspec.NoSuchKernel: No such kernel named XXX

### ISSUE THREAD

**Issue by crawles** [jupyter/kernel_gateway#190]
Ran into this issue by creating a notebook in one environment and then trying to run in a different environment jupyter gateway with notebook-http personality. Both environments are running Python 3.5.2

The issue comes from jupytergateway.py, which gets the kernel name from the .ipynb file:

`kernel_name = notebook['metadata']['kernelspec']['name']`

Creating the notebook in this first environment, which I had installed Python 3 using [these instructions](https://www.continuum.io/blog/developer-blog/python-3-support-anaconda) creates a .ipynb file with this metadata:

```
 "metadata": {
  "kernelspec": {
   "display_name": "Python [py35]",
   "language": "python",
   "name": "Python [py35]"
```

However the second environment doesn't have a kernel called "Python [py35]" thus the gateway command

`jupyter-kernelgateway --KernelGatewayApp.api=notebook-http\
                                     --KernelGatewayApp.seed_uri='test35.ipynb'`

 fails with:

```
ERR   File "/home/vcap/app/.conda/envs/dep_env/lib/python3.5/site-packages/kernel_gateway/gatewayapp.py", line 248, in _load_notebook
ERR     self.kernel_spec_manager.get_kernel_spec(kernel_name)
ERR   File "/home/vcap/app/.conda/envs/dep_env/lib/python3.5/site-packages/jupyter_client/kernelspec.py", line 175, in get_kernel_spec
ERR     raise NoSuchKernel(kernel_name)
ERR jupyter_client.kernelspec.NoSuchKernel: No such kernel named Python [py35]
```

The Python 3 kernel in the second environment is named "python3". I can get the code to work if I edit the metadata of the .ipynb file and change the name to "python3", though this seems not ideal. A potential solution would be if there was an option to force evaluation using a specified kernel name. E.g.,

-- KernelGatewayApp.kernel_name = "python3"

**Comment by crawles** [comment]
related https://github.com/conda/conda/issues/3094

**Comment by parente** [comment]
The other solution is to make sure the environment used during development of the notebook is available to the kernel gateway. In fact, this is the only real way to ensure reproducibility between the notebook and kernel gateway.

Forcing a specific kernel via the command line when the notebook metadata is requesting something else feels wrong, though I'm not sure what the best practice is here.

**Comment by crawles** [comment]
Agreed about other solution of same environments and think this would be best case scenario when possible. IMO there should be another solution when this is not the case- e.g., using jupyter gateway to deploy model on a production server that has a different environment than the developer is using. 

The current solution to opening a .ipynb file with unknown kernel in the notebook prompts the user to select an available kernel:

![image](https://cloud.githubusercontent.com/assets/5091145/17902075/c58ea9c8-6933-11e6-9bda-c8b6b0092a0f.png)

**Comment by parente** [comment]
> using jupyter gateway to deploy model on a production server that has a different environment than the developer is using

The kernel name mismatch is the least of your worries when prod environment doesn't match dev. But I get your point. The kernel name field is sort of a wild west where python3-with-extra-stuff-in-the-env is a valid name. Letting ops override what's captured in the notebook seems reasonable for tackling this part of the env mismatch problem.
