### ISSUE TITLE
How to specify seed URI or switch on notebook-http mode using a running kernel gateway?

### ISSUE THREAD

**Issue by rs2** [jupyter/kernel_gateway#191]
1. Start the gateway using `jupyter kernelgateway --KernelGatewayApp.ip=0.0.0.0`
2. How to enable the `notebook-http` mode using the above `gateway` process, e.g. how to set `KernelGatewayApp.seed_uri=/foo/bar.ipynb`?

Ref: https://jupyter-kernel-gateway.readthedocs.io/en/latest/http-mode.html

**Comment by parente** [comment]
The running section on that page has a complete command line example:

https://jupyter-kernel-gateway.readthedocs.io/en/latest/http-mode.html#running

**Comment by rs2** [comment]
Thank you, I am well familiar with those. My question is, once kernel gateway is started `without` the `seed_uri` argument, is there a way to specify such a notebook (or a cell?) using the API?

**Comment by rs2** [comment]
Is there a swagger spec that one can have a look at?

`/_api/spec/swagger.json` says `{"reason": "Not Found", "message": ""}`
`/api` says `{"version": "4.2.1"}`

**Comment by nitind** [comment]
@rs2 No, it is not something you can change and have properly reflected after the Kernel Gateway is already up and running. When in notebook-http mode, the swagger will reflect the seed notebook. In which mode did you get what I have to guess was a 404?

**Comment by parente** [comment]
If the 404 came from fetching the swagger using the latest pypi kernel gateway package at the time, then #208 should be the fix.

Changing the notebook providing the API at runtime would require restarting kernels, parsing the notebook, and dynamically changing the registered tornado handlers at a minimum. I think we would only consider merging a PR implementing that if it could be done without massive additions to the code base and with many new tests.
