### ISSUE TITLE
No such kernel named conda-root-py

### ISSUE THREAD

**Issue by awenhu** [jupyter/kernel_gateway#197]
[KernelGatewayApp] Searching [u'/root', '/root/.jupyter', '/mnt/anaconda2/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'] fo
r config files  
[KernelGatewayApp] Looking for jupyter_config in /etc/jupyter  
[KernelGatewayApp] Looking for jupyter_config in /usr/local/etc/jupyter  
[KernelGatewayApp] Looking for jupyter_config in /mnt/anaconda2/etc/jupyter  
[KernelGatewayApp] Looking for jupyter_config in /root/.jupyter  
[KernelGatewayApp] Looking for jupyter_config in /root  
[KernelGatewayApp] Looking for jupyter_kernel_gateway_config in /etc/jupyter  
[KernelGatewayApp] Looking for jupyter_kernel_gateway_config in /usr/local/etc/jupyter  
[KernelGatewayApp] Looking for jupyter_kernel_gateway_config in /mnt/anaconda2/etc/jupyter  
[KernelGatewayApp] Looking for jupyter_kernel_gateway_config in /root/.jupyter  
[KernelGatewayApp] Looking for jupyter_kernel_gateway_config in /root  
[KernelGatewayApp] Found kernel python2 in /usr/local/share/jupyter/kernels  
Traceback (most recent call last):  
  File "/mnt/anaconda2/bin/jupyter-kernelgateway", line 11, in <module>  
    sys.exit(launch_instance())  
  File "/mnt/anaconda2/lib/python2.7/site-packages/jupyter_core/application.py", line 267, in launch_instance  
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)  
  File "/mnt/anaconda2/lib/python2.7/site-packages/traitlets/config/application.py", line 595, in launch_instance  
    app.initialize(argv)  
  File "/mnt/anaconda2/lib/python2.7/site-packages/kernel_gateway/gatewayapp.py", line 298, in initialize  
    self.init_configurables()  
  File "/mnt/anaconda2/lib/python2.7/site-packages/kernel_gateway/gatewayapp.py", line 317, in init_configurables  
    self.seed_notebook = self._load_notebook(self.seed_uri)  
  File "/mnt/anaconda2/lib/python2.7/site-packages/kernel_gateway/gatewayapp.py", line 284, in _load_notebook  
    self.kernel_spec_manager.get_kernel_spec(kernel_name)  
  File "/mnt/anaconda2/lib/python2.7/site-packages/jupyter_client/kernelspec.py", line 175, in get_kernel_spec  
    raise NoSuchKernel(kernel_name)  
jupyter_client.kernelspec.NoSuchKernel: No such kernel named conda-root-py 

thanks in advance

**Comment by parente** [comment]
@awenhu Can you share the command you're using to start the kernel gateway?

**Comment by awenhu** [comment]
jupyter kernelgateway --KernelGatewayApp.api=notebook-http --KernelGatewayApp.ip=0.0.0.0 --KernelGatewayApp.port=15001 --KernelGatewayApp.prespawn_count=2 --KernelGatewayApp.seed_uri='/root/yongli/DTU_Count_15001.ipynb' --KernelGatewayApp.allow_origin=* --debug

**Comment by parente** [comment]
The `DTU_Count_15001.ipynb` notebook must have been written in a notebook server that has a kernel named `conda-root-py`. That kernel + conda environment must not be available wherever you're running the kernel gateway. Either you have to make sure it is or specify an equivalent alternative using the `KernelGatewayApp.force_kernel_name` parameter.

**Comment by awenhu** [comment]
how to install conda-root-py?
if using KernelGatewayApp.force_kernel_name, what value should be set?

**Comment by parente** [comment]
`conda-root-py` looks like it's a default kernel spec created by anaconda in your notebook server environment. You'll need to create an equivalent conda environment on the machine where you plan to run the kernel gateway (KG) server with whatever packages your notebook is using. Assuming you're trying to run this on a different machine from the one where you're running the notebook server, the general idea is something like:

```
conda create -n conda-root-py python=<whatever version you're using> <other packages your notebook needs here> ipykernel
source activate conda-root-py
python -m ipykernel install --name='conda-root-py' --display-name='Python [conda root]' --user
source deactivate
# now run kernel gateway
```

If you're running the kernel gateway on the **same** machine as your notebook server and as the same user, then let me know because it might be a bug.

**Comment by awenhu** [comment]
same server

**Comment by parente** [comment]
OK. What's the output of `jupyter kernelspec list`?

**Comment by parente** [comment]
@awenhu I'm going to close this issue as inactive. If you did find a solution to your problem, please share it here. If not, and you can provide the kernelspec list output, we can continue debugging.

**Comment by raphaelshirley** [comment]
I am having problems to this very frequently. Can someone explain how the following:

jupyter kernelspec list
jupyter nbconvert --to notebook --execute 2_Merging.ipynb --output 2-out.ipynb --ExecutePreprocessor.kernel_name=helpint

yields the following output:

Available kernels:
  helpint    /mnt/pact/rs548/.local/share/jupyter/kernels/helpint
  python3    /research/astro/fir/HELP/help_python/miniconda3/envs/herschelhelp_internal/share/jupyter/kernels/python3

[NbConvertApp] Converting notebook 2_Merging.ipynb to notebook
[NbConvertApp] Executing notebook with kernel: helpint
Traceback (most recent call last):
  File "/research/astro/fir/HELP/help_python/miniconda3/envs/herschelhelp_internal/lib/python3.6/site-packages/jupyter_client/kernelspec.py", line 201, in get_kernel_spec
    resource_dir = d[kernel_name.lower()]
KeyError: 'helpint'

...

jupyter_client.kernelspec.NoSuchKernel: No such kernel named helpint

i.e. Jupyter seems to have access to the kernel helpint but then when I run nbconvert at the command line it doesn't seem to have access to it.

I have seen a lot of questions about this error but no satisfactory solution.

Many thanks for any everyone who has commented so far.

**Comment by rolweber** [comment]
@raphaelshirley: Asking questions on closed issues is not a good way to get help. Neither is asking questions about nbformat in the issue tracker of kernel_gateway. Now, trying to help you anyway:

The way I read that output, you don't have a kernel named `helpint`. You do seem to have a kernel named `helpint /mnt/pact/rs548/.local/share/jupyter/kernels/helpint` though.

**Comment by raphaelshirley** [comment]
Sorry about that. I am unfamiliar with the GitHub help system, and the problem seemed related but I see now why that is the wrong subject. I won't do that again and thanks very much for responding. That is interesting, I will try to specify the kernel name with the full path. I didn't think names could have spaces in, perhaps I should try

ExecutePreprocessor.kernel_name="helpint /mnt/pact/rs548/.local/share/jupyter/kernels/helpint"
