### ISSUE TITLE
Does kernel gateway support HTTPS connections?

### ISSUE THREAD

**Issue by rolweber** [jupyter/kernel_gateway#202]
The documentation [1] does not list options that correspond with `NotebookApp.keyfile`, `NotebookApp.certfile` or `NotebookApp.client_ca` [2] to support encrypted communication [3].

[1] https://jupyter-kernel-gateway.readthedocs.io/en/latest/config-options.html
[2] http://jupyter-notebook.readthedocs.io/en/latest/config.html
[3] http://jupyter-notebook.readthedocs.io/en/latest/public_server.html#using-ssl-for-encrypted-communication

**Comment by parente** [comment]
Not yet. The options:

https://github.com/jupyter/notebook/blob/e6fb7e65e94f6dd94fc5aba0cbe4bd3065e19623/notebook/notebookapp.py#L526

and code for passing them to the tornado http server instance:

https://github.com/jupyter/notebook/blob/e6fb7e65e94f6dd94fc5aba0cbe4bd3065e19623/notebook/notebookapp.py#L1066

need to be ported here.

**Comment by rolweber** [comment]
Thanks for the prompt response. I'll leave the issue open as a feature request.

**Comment by parente** [comment]
Happy to take a PR for it too. It's mostly adding traitlets.

**Comment by rolweber** [comment]
My employer requires some legal approvals before I'm allowed to contribute to an OSS project - you might remember ;-) I've triggered the necessary clearance processes, but it may take a while to complete them. The changes themselves were easy enough.
