### ISSUE TITLE
What could be causing an HTTP 403 error?

### ISSUE THREAD

**Issue by MaximilianR** [jupyter/kernel_gateway#203]
When I try and connect to the running kernel, from Hydrogen, I get a 403 code:

```
[I 161201 19:03:02 web:1908] 200 GET /api/kernelspecs?1480636982374 (127.0.0.1) 3.82ms
[W 161201 19:03:02 web:1493] 403 GET /api/sessions?1480636982420 (127.0.0.1): Forbidden
[W 161201 19:03:02 web:1908] 403 GET /api/sessions?1480636982420 (127.0.0.1) 0.96ms
```

I'm using the default `jupyter_kernel_gateway_config.py`. 

I use a notebook with a password & HTTPS, but my understanding was the notebook config file wouldn't be picked up (and it's not listed in `--debug` mode

Any ideas why a 403 would be returned?

Many thanks,
Max

**Comment by parente** [comment]
Session and kernel listing are not enabled by default in the kernel gateway for privacy. You have to pass `--JupyterWebsocketPersonality.list_kernels=True` or set the environment variable `KG_LIST_KERNELS=True` when starting the kernel gateway.
