### ISSUE TITLE
GET /api/swagger.yaml delivers 404: Not Found

### ISSUE THREAD

**Issue by skyhias** [jupyter/kernel_gateway#207]
When installing kernel_gateway via pip, `GET /api/swagger.yaml` is not working, because swagger.yaml is missing in the installation.

After changing in MANIFEST.in
`include kernel_gateway/services/api/swagger.*`
to
`include kernel_gateway/jupyter_websocket/swagger.*`
and reinstalling it works.

**Comment by Lull3rSkat3r** [comment]
#208 should close this.
