### ISSUE TITLE
Can't follow development Workflow missing "image" target in makefile

### ISSUE THREAD

**Issue by garywu** [jupyter/kernel_gateway#219]
https://github.com/jupyter/kernel_gateway/commit/c71091a6cd03bcc50aed6ee2172d9f7edb2014fc removed all reference to docker from the makefile. 

Following step in Development Workflow in [devinstall](https://github.com/jupyter/kernel_gateway/blame/master/docs/source/devinstall.md#L32) 
 no longer works:

> Build a Docker image containing additional dev libraries.
> make image

What are the new steps?

**Comment by parente** [comment]
Thanks for the report. I'll make sure the README gets update as part of the next release.
