### ISSUE TITLE
Restart Kernel in notebook-http mode

### ISSUE THREAD

**Issue by RDegnen** [jupyter/kernel_gateway#223]
Hello, I've been looking around previous issues and the docs but I can't seem to find an answer. Is it possible to restart the kernel in notebook-http mode via a request? I have tried sending a request to a cell that calls `os._exit(00)` but that just throws an error and I get no response back. Also I am not running this in docker, just notebook-http mode on its own, thanks!

**Comment by parente** [comment]
There's not way to restart the kernel at the moment. Can you describe your use case?

**Comment by RDegnen** [comment]
I'm running cells in a notebook that connect to a spark cluster. After stopping the spark context, I can only seem to create a new one if I restart the kernel. I wanted to just have the kernel gateway running in the background so we can automate the running of our notebooks from a remote server, instead of having to fire up the kernel every time we run and notebook and then manually killing the process.

**Comment by parente** [comment]
> After stopping the spark context, I can only seem to create a new one if I restart the kernel. 

What version of Spark are you using? Can you include the exception you get from Spark about trying to create a new context after stopping a prior one?

**Comment by RDegnen** [comment]
Hey I figured out a work around, by just starting and stopping jupyter kernel gateway with some scripts over ssh.

**Comment by facutk** [comment]
@RDegnen I'm running into the same issue... would you mind sharing your ssh scripts?
