### ISSUE TITLE
Documentation updates to clarify kernel_gateway's purpose

### ISSUE THREAD

**Issue by BigLep** [jupyter/kernel_gateway#229]
Hello,

Feel free to resolve/ignore, but I found that the docs under the kernel_gateway GitHub project weren't as helpful for communicating the problem that kernel_gateway is attempting to solve vs. http://blog.jupyter.org/2016/03/09/jupyter-kernel-gateway/ and https://github.com/jupyter-incubator/proposals/blob/master/kernel_gateway/proposal.md .  I'm only bringing this up because wouldn't want someone to prematurely discount/disregard the project.

Steve

**Comment by parente** [comment]
Thanks for the feedback, @BigLep. If you have some time to contribute, we'll gladly take pull requests that improve the documentation. If not, we can try to work in some of the wording from the blog posts and proposal over time.
