### ISSUE TITLE
Developer docs: Testing with different Python versions

### ISSUE THREAD

**Issue by rolweber** [jupyter/kernel_gateway#231]
When following the current [instructions](https://jupyter-kernel-gateway.readthedocs.io/en/latest/devinstall.html) for setting up the development environment, you get a Python 3.6 environment. Instructions for running unit tests and starting servers are for this default environment.

Shouldn't there be instructions and `make` targets for setting up and running unit tests with the minimum required versions of Python 3.x and Python 2.x, respectively? I'm not sure what those minimum versions are though.

**Comment by parente** [comment]
The [.travis.yml](https://github.com/jupyter/kernel_gateway/blob/master/.travis.yml#L4) configures Travis CI to run the tests on five versions of Python KG supports.

It's possible to add a variable to the Makefile to let the user pick which version of Python he/she wants to use when creating the conda environment. Creating conda environments multiple versions and having separate make targets for each makes a mess, and is one of the reasons the build/test process moved off of the docker stack images.

**Comment by rolweber** [comment]
OK, makes sense. So I'll have to open a PR to get my changes tested by Travis.
