### ISSUE TITLE
Swagger: auth token

### ISSUE THREAD

**Issue by rolweber** [jupyter/kernel_gateway#232]
According to swagger.yaml, only `/api/kernelspecs` requires the auth token.
https://github.com/rolweber/kernel_gateway/blob/e897143cb8ff84a9f52819005524f168675966cb/kernel_gateway/jupyter_websocket/swagger.yaml#L72

I thought it is required for all calls, if configured? Should swagger list the token as a top-level `security` element? If there are only few calls which do not require the token, it would still be easier to exempt those than to add the token to many calls individually.

**Comment by parente** [comment]
That was a copy/paste mistake, and PR #227 fixes it. It might be worth calling out in the top level security section how auth is handled globally.
