### ISSUE TITLE
Kernel Gateway Uncaught Exception

### ISSUE THREAD

**Issue by ytang327** [jupyter/kernel_gateway#241]
The following is the environment: 

On an x/86 system, I have a jupyter notebook server running. On a z/OS system, I have a Jupyter Kernel Gateway running. The notebook server connects to the kernel gateway which gives the server access to Apache Toree (dev8) . Apache Toree then interacts with the Spark cluster (2.0.2) The scala version is 2.11.8

I am trying to run a jupyter notebook with visualizations using Brunel 2.3.

Most of the brunel visualizations work i.e. 

%%brunel data('df') x(_1) y(_2) bar style("fill:red") filter(_1:2) :: width=300, height=300

or 

%%brunel  map('uk','france','spain','germany')

However, any brunel commands that contain "opacity(#selection)" i.e. 

%%brunel data('df') x(_1) y(_2) bar opacity(#selection) style("fill:red") filter(_1:2) :: width=300, height=300

kernel gateway spits out the following log message:

[E 170413 15:16:27 web:1548] Uncaught exception GET /api/kernels/e6f0c109-d3b2-4254-85a6-1eea95f7175b/channels (9.12.41.240)
    HTTPServerRequest(protocol='http', host='9.12.41.72:9099', method='GET', uri='/api/kernels/e6f0c109-d3b2-4254-85a6-1eea95f7175b/channels', version='HTTP/1.1', remote_ip='9.12.41.240', headers={'Upgrade': 'websocket', 'Accept-Encoding': 'gzip', 'Sec-Websocket-Version': '13', 'Connection': 'Upgrade', 'Sec-Websocket-Key': 'evzOnn7Up3BD/6Grb87mCQ==', 'Host': '9.12.41.72:9099', 'Authorization': 'token commander'})
    Traceback (most recent call last):
      File "/Voyager/Hamlet/python/python-2017-04-12-py27/python27/lib/python2.7/site-packages/tornado/web.py", line 1425, in _stack_context_handle_exception
        raise_exc_info((type, value, traceback))
      File "/Voyager/Hamlet/python/python-2017-04-12-py27/python27/lib/python2.7/site-packages/tornado/stack_context.py", line 314, in wrapped
        ret = fn(*args, **kwargs)
      File "/Voyager/Hamlet/python/python-2017-04-12-py27/python27/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 191, in <lambda>
        self.on_recv(lambda msg: callback(self, msg), copy=copy)
      File "/Voyager/Hamlet/python/python-2017-04-12-py27/python27/lib/python2.7/site-packages/jupyter_kernel_gateway-1.2.1-py2.7.egg/kernel_gateway/services/kernels/handlers.py", line 172, in _on_zmq_reply
        super(ZMQChannelsHandler, self)._on_zmq_reply(stream, msg_list)
      File "/Voyager/Hamlet/python/python-2017-04-12-py27/python27/lib/python2.7/site-packages/notebook/services/kernels/handlers.py", line 296, in _on_zmq_reply
        msg = self.session.deserialize(fed_msg_list)
      File "/Voyager/Hamlet/python/python-2017-04-12-py27/python27/lib/python2.7/site-packages/jupyter_client/session.py", line 859, in deserialize
        raise ValueError("Invalid Signature: %r" % signature)
    ValueError: Invalid Signature: '4324e46ac9c58336e781be2bff631fb7e3019f1ce58f5795544a8d54cdfa0f0a'

If I remove the "opacity(#selection)" it works just fine. I haven't been able to decipher what this error message is telling me.

**Comment by parente** [comment]
What version of kernel gateway and jupyter notebook do you have installed in that python environment?

**Comment by ytang327** [comment]
Kernel gateway 1.2.1 and jupyter notebook 4.3.x ... It is within a docker container (based off image jupyter/minimal-notebook)

**Comment by rolweber** [comment]
One thing to watch out for are the Java default character encodings on z. Maybe the `#` is incorrectly converted to a different character, leading to a signature mismatch. If default character encodings use a z-specific code page, try changing them to utf-8.

I'm not sure which version of Toree you are using. There's no dev8 here:
https://github.com/apache/incubator-toree/releases

But there are Toree fixes which might play a role, and which have not even been released yet. Like:
https://github.com/apache/incubator-toree/pull/111

If the character encodings don't lead anywhere, could you build a Toree version from the current master and try with that?

**Comment by parente** [comment]
@ytang327 Does the same exception occur in plain old Jupyter Notebook when you run that code?

**Comment by ytang327** [comment]
@parente The same exception does not occur if I run Jupyter notebook alone without kernel gateway. It runs as expected. 

@rolweber The most current Toree version I am running is what was in the master branch about a week ago. I will look into the character encodings on z

**Comment by ytang327** [comment]
@rolweber I'm not sure if it's a # symbol problem, if I run a different command with # i.e.

%%brunel data('df') x(_1) y(_2) bar style("fill:red") color(#count) filter(_1:2) :: width=300, height=300

I do not run into the exception as shown above and it shows the visualization as expected in the notebook.

**Comment by parente** [comment]
> The same exception does not occur if I run Jupyter notebook alone without kernel gateway. It runs as expected.

Sorry. I meant if you run the notebook server on the z/os system. But as I think about that, it's likely impossible for you to try and would likely lead to the same error anyway as the stack trace clearly shows it's the `compare_digest` code in https://github.com/jupyter/jupyter_client/blob/master/jupyter_client/session.py#L897 that is failing.

The code is checking the signature on a message sent from the toree kernel back to the notebook/kernel gateway server. I suspect @rolweber is right that the fields used to compute the signature check on the server side differs from what the Toree used to compute the signature on the kernel side. Short of looking at encodings, turning up the logging on the Toree kernel to see the message content and likewise the logging on the server side to see the messages it is receiving are your best bet. I bet the difference will pop out at you if you can see the message sent by the kernel vs the message received by the KG/notebook server.

**Comment by ytang327** [comment]
@parente I was speaking with Dan (one of the main developers to the Brunel visualization package) he had mentioned that when using #selection a utf-8 can be included in the JS. I'm wondering if python 2.7 is having trouble with this character and maybe the server side is interpreting it differently from the kernel side? 

Also I used the "--debug" option in jupyter kernel gateway and rebuilt toree to also set the log level to "DEBUG" However, this didn't seem to give me much more information other than the Web Socket being closed (last line in the following log messages)

[E 170421 08:18:16 web:1548] Uncaught exception GET /api/kernels/dbc17f01-9f7e-4556-8f00-1f61c6c04241/channels (9.12.41.240)
    HTTPServerRequest(protocol='http', host='9.12.41.72:9099', method='GET', uri='/api/kernels/dbc17f01-9f7e-4556-8f00-1f61c6c04241/channels', version='HTTP/1.1', remote_ip='9.12.41.240', headers={'Upgrade': 'websocket', 'Accept-Encoding': 'gzip', 'Sec-Websocket-Version': '13', 'Connection': 'Upgrade', 'Sec-Websocket-Key': 'ytyAbtNTIZbGCkd9BNRP8Q==', 'Host': '9.12.41.72:9099', 'Authorization': 'token commander'})
    Traceback (most recent call last):
      File "/Voyager/Hamlet_TARS/python/python-2017-04-12-py27/python27/lib/python2.7/site-packages/tornado/web.py", line 1425, in _stack_context_handle_exception
        raise_exc_info((type, value, traceback))
      File "/Voyager/Hamlet_TARS/python/python-2017-04-12-py27/python27/lib/python2.7/site-packages/tornado/stack_context.py", line 314, in wrapped
        ret = fn(*args, **kwargs)
      File "/Voyager/Hamlet_TARS/python/python-2017-04-12-py27/python27/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 191, in <lambda>
        self.on_recv(lambda msg: callback(self, msg), copy=copy)
      File "/Voyager/Hamlet_TARS/python/python-2017-04-12-py27/python27/lib/python2.7/site-packages/jupyter_kernel_gateway-1.2.1-py2.7.egg/kernel_gateway/services/kernels/handlers.py", line 172, in _on_zmq_reply
        super(ZMQChannelsHandler, self)._on_zmq_reply(stream, msg_list)
      File "/Voyager/Hamlet_TARS/python/python-2017-04-12-py27/python27/lib/python2.7/site-packages/notebook/services/kernels/handlers.py", line 296, in _on_zmq_reply
        msg = self.session.deserialize(fed_msg_list)
      File "/Voyager/Hamlet_TARS/python/python-2017-04-12-py27/python27/lib/python2.7/site-packages/jupyter_client/session.py", line 859, in deserialize
        raise ValueError("Invalid Signature: %r" % signature)
    ValueError: Invalid Signature: 'c2f6182d0e31d8e73cede52c678f360380dbf1ec5c9063fb3a7185544ddbc48a'
[KernelGatewayApp] Websocket closed dbc17f01-9f7e-4556-8f00-1f61c6c04241:ef28a1fe-a88e-4a5f-a30f-43bdc0feb216

**Comment by ytang327** [comment]
@parente @rolweber  When the message/signature list is sent back to notebook/kernel gateway server, is it already utf-8 encoded? I am running python 2.7 so I'm wondering if it is treating the utf-8 encoded string as ascii encoded. 

I noticed where the problem was by the way. It seems that when the signature is checked in the jupyter_client code there is a mismatch because it is not interpreting some of the unicode characters correctly that is sent back from toree. Instead, they are converted to 0x3F which is a "?"

**Comment by parente** [comment]
> It seems that when the signature is checked in the jupyter_client code there is a mismatch because it is not interpreting some of the unicode characters correctly that is sent back from toree.

Is toree encoding all of its message strings to utf-8 before putting them on the wire to send out? I can't find doc on it, but I suspect the jupyter protocol assumes everything is utf-8 encoded.

**Comment by ytang327** [comment]
@parente Turned out the problem was setting the java options to utf-8, that was why it was not being encoded correctly. I will go ahead and close this issue
