### ISSUE TITLE
allow_headers option overwritten

### ISSUE THREAD

**Issue by jeremysalwen** [jupyter/kernel_gateway#243]
python -m kernel_gateway --KernelGatewayApp.allow_origin='*' --KernelGatewayApp.allow_headers='X-XSRFToken'

Should return headers
    Access-Control-Allow-Headers: X-XSRFToken

But instead for some API calls it returns:
    Access-Control-Allow-Headers: 'accept, content-type, authorization'

It seems that this is overwritten in line 452 of notebook/base/handlers.py

**Comment by jeremysalwen** [comment]
python -m kernel_gateway --KernelGatewayApp.allow_origin='*' --KernelGatewayApp.allow_headers='X-XSRFToken'

Should return headers
    Access-Control-Allow-Headers: X-XSRFToken

But instead for some API calls it returns:
    Access-Control-Allow-Headers: 'accept, content-type, authorization'

It seems that this is overwritten in line 452 of notebook/base/handlers.py

**Comment by rolweber** [comment]
Thanks for pinpointing the offending statement. Could you provide an example for an API call that returns the wrong header? That will make it easier to reproduce the problem.

**Comment by jeremysalwen** [comment]
`curl 'http://localhost:8888/api/kernelspecs?1493755508377' -X OPTIONS -H 'Host: localhost:8888' --compressed -H 'Access-Control-Request-Method: GET' -H 'Access-Control-Request-Headers: content-type,x-xsrftoken' -H 'Origin: http://localhost:4200' -H 'Connection: keep-alive' -H 'Cache-Control: max-age=0'
`
returns Access-Control-Allow-Headers: accept, content-type, authorization

same for /api/sessions

**Comment by parente** [comment]
KG overrides `set_default_headers()` but the notebook has the Tornado `options()` handler implemented to return a hardcoded set of allowed methods and headers. I'm working on a fix.
