### ISSUE TITLE
Kernel Gateway APIs are slow while the same cells in jupyter notebook run fast.

### ISSUE THREAD

**Issue by cheekala** [jupyter/kernel_gateway#253]
Running Kernel Gateway in the following mode. 
nohup jupyter kernelgateway --KernelGatewayApp.api='kernel_gateway.notebook_http' --KernelGatewayApp.ip=0.0.0.0 --KernelGatewayApp.seed_uri='/home/ubuntu/ABC.ipynb' >> /home/ubuntu/jupyter_kernel.log 2>&1 &

There is only one API annotated in the notebook, ABC.ipynb. Followed is the output log on server. 

[KernelGatewayApp] Kernel started: e154f902-1e7c-4f6f-a784-4441e6eb7d7b
[KernelGatewayApp] Registering resource: /pha/v1.0/converse, methods: (['POST'])
[KernelGatewayApp] Registering resource: /_api/spec/swagger.json, methods: (GET)
[KernelGatewayApp] The port 8888 is already in use, trying another port.
[KernelGatewayApp] Jupyter Kernel Gateway at http://0.0.0.0:8889
2017-06-09 04:30:32.021401: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-06-09 04:30:32.021448: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-06-09 04:30:32.021472: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-06-09 04:30:32.021479: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2017-06-09 04:30:32.021483: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
2017-06-09 04:30:32.172746: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:901] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2017-06-09 04:30:32.173276: I tensorflow/core/common_runtime/gpu/gpu_device.cc:887] Found device 0 with properties:
name: Tesla K80
major: 3 minor: 7 memoryClockRate (GHz) 0.8235
pciBusID 0000:00:1e.0
Total memory: 11.17GiB
Free memory: 11.11GiB
2017-06-09 04:30:32.173304: I tensorflow/core/common_runtime/gpu/gpu_device.cc:908] DMA: 0
2017-06-09 04:30:32.173311: I tensorflow/core/common_runtime/gpu/gpu_device.cc:918] 0:   Y
2017-06-09 04:30:32.173330: I tensorflow/core/common_runtime/gpu/gpu_device.cc:977] Creating TensorFlow device (/gpu:0) -> (device: 0, name: Tesla K80, pci bus id: 0000:00:1e.0)
INFO:tornado.access:201 POST /pha/v1.0/converse?uid=100000000143&resp=yes (106.51.37.204) **57761.93ms**
INFO:tornado.access:201 POST /pha/v1.0/converse?uid=100000000143&resp=yes (106.51.37.204) **42680.99ms**

**The above API is running under a second in the jupyter notebook, and here the API is taking more than 40 secs. Couldn't understand though, why!?**

**Comment by rolweber** [comment]
That's hard to tell without seeing the actual code or knowing the environment.
Maybe some of the non-annotated cells in your notebook set parameters for TensorFlow which affect the performance?
Maybe you're running the notebook server with a different version of TensorFlow, one that was compiled to use all the special instruction sets mentioned in the warnings?

**Comment by cheekala** [comment]
There are **no non-annotated cells**, all cells are annotated to only one API. 
My notebook is running with tensorflow verion 1.1.0-rc2. Kernel gateway is using the same tensorflow version too.

**Comment by rolweber** [comment]
Assuming it's the same machine, and the same kernel spec, see if you can spot a difference in the environment. If it's a Python notebook: `!printenv | sort`
Watch out for  library search paths and the like.

**Comment by rolweber** [comment]
When you're measuring the execution time in Jupyter notebook, are you also running _all_ cells? It's somewhat unusual that to observe a sub-second execution time for a "Run all cells" operation. I certainly couldn't guess with that accuracy if I have to scroll the notebook to see when it's finished executing.

**Comment by cheekala** [comment]
Followed are the environment differences.. I don't see actually much difference except the following. 

**Notebook Environment had these two additional variables.**
OLDPWD=/home/ubuntu/semafor
PS1=(tensorflow) \[\e]0;\u@\h: \w\a\]${debian_chroot:+($debian_chroot)}\u@\h:\w\$ 

**Kernel Environment had this additional variable**
KERNEL_GATEWAY=1

and one variable is differed 
_=/usr/bin/printenv (on Kernel)
_=/usr/bin/nohup (on Notebook) 

Please find the environment files here.  
[notebookEnv.txt](https://github.com/jupyter/kernel_gateway/files/1063427/notebookEnv.txt)
[kernelEnv.txt](https://github.com/jupyter/kernel_gateway/files/1063431/kernelEnv.txt)

I've time.time() as the 1st line in the 1st cell, and time.time() as the last line in the last cell, I'm taking the difference and sending it back in the response json. 
**This is my observation, It's not that kernel is running the cells slow, in stead, kernel is spending ~40 seconds to even start the cell execution. Both modes, have the same execution times otherwise.** 

kernel seems to be doing some work before starting the cell execution.

**Comment by cheekala** [comment]
One more thing, This was all working fine, until a few weeks ago when I upgraded my tensorflow environment. Since then, I'm seeing the delays in the APIs.

**Comment by rolweber** [comment]
Thanks for digging into this. Now we know we have to look for the problem in a different place.

**Comment by rolweber** [comment]
How many cells does your notebook have? How big is the notebook file?
Does it make a difference if you clear all cell output before saving, and then run KG on the smaller file?

I'm wondering if there's some inefficiency when the notebook_http module collects the cells to be executed for the request.

**Comment by cheekala** [comment]
Notebook has just one POST API, spread across 15 cells, 64KB file size on disk (after clearing all outputs). 
No difference in the time on a smaller file. 

I'd like to bring your attention to two things, once again humbly. 
1. Tensorflow was upgraded to 1.1.. few weeks ago, and observing the slower API execution times 
2. The CELL execution times remain same whether it's Notebook or KG (under 1 sec), this probably means, KG is spending time in doing some things, may be what you have suggested above.

**Comment by parente** [comment]
The kg parses all cells once at startup. It then executes all non annotated cells once from top to bottom. Next  it prints the paths to the console and starts listening for http requests. When one is received it sends the string text of the code from the associated cells to the kernel for evaluation. It listens for all messages from the kernel until an idle status messages is received. Finally, it sends some of the messages collected before that idle indicator as the http response.


Is the cell with the http handler code particularly long? Does it emit a lot of output? Can you share a version of your notebook that reproduces the problem? Apologies if you have and I missed it above.

**Comment by cheekala** [comment]
Please find the notebook here. It doesn't emit any output. 

[DC DL API.zip](https://github.com/jupyter/kernel_gateway/files/1065823/DC.DL.API.zip)

**Comment by parente** [comment]
Try removing the `POST` annotation from all of the cells before the one with `req = json.loads(REQUEST)`. As I noted above, the kernel gateway will execute all cells that don't have an annotation from top to bottom *once* when the kernel starts. Therefore, you don't need to have any of the try/except clauses guarding your run-once code. More importantly, the kernel gateway will not need to send all of those code cells to the kernel evaluation on every request, only to have them do nothing. I am almost certain this is a source of slowness, regardless of tensorflow version updates.

**Comment by cheekala** [comment]
Have done the suggested changes. Now, the API load time comes down to **14 seconds** from **40 seconds**.  How can we further skim this time down??

**Comment by rolweber** [comment]
Try switching back to the older Tensorflow version. If that gets rid of the delay, you'll have to work with the Tensorflow community to find out what you need to change to make the newer version start fast.

**Comment by parente** [comment]
Cleaning up the POST annotations reduced the overhead for execution input. I would also suggest you check for output. Is the new version of tensorflow printing, logging, or emittting any other kind of output that would make its way back to the kernel gateway and need to be processed?

**Comment by cheekala** [comment]
Switched to older tensorflow version **0.12.0** and checked, API load time is reduced from **14 seconds** to **5 seconds**. 

**Cleaning up the POST annotations reduced the overhead for execution input.** - Can you elaborate this a little !?

**Is the new version of tensorflow printing, logging, or emittting any other kind of output that would make its way back to the kernel gateway and need to be processed?** - There is certain other output, not that is of interest to Kernel Gateway.

**Comment by parente** [comment]
> There is certain other output, not that is of interest to Kernel Gateway.

Yes, but if this is is output on stdout or stderr when cells execute, KG still has to receive it all and decide whether its part of the REST API response or not.

**Comment by cheekala** [comment]
Few warning messages like the following are coming in some cases. 4-5 such warnings are emitted at maximum. 

**/usr/local/lib/python3.4/dist-packages/ipykernel/__main__.py:124: RuntimeWarning: invalid value encountered in true_divide**

**Comment by parente** [comment]
@cheekala this thread has been quiet for a couple months now. Did you spend any more time debugging the performance issue?
