### ISSUE TITLE
Issue with using auth_token and CORS requests 

### ISSUE THREAD

**Issue by SimonBiggs** [jupyter/kernel_gateway#257]
When issuing a CORS request the browser sends a preflight OPTIONS http request. The browser doesn't put the token in this request. As a result kernel_gateway rejects the request.

This conflict appears to make CORS and auth_tokens not currently compatible. I've provided more details over at https://github.com/jupyterlab/jupyterlab/issues/2960

A solution might be to check if the request type is OPTIONS, if it is, then don't require the token to be provided.

I'd be happy to attempt a pull request. What are your thoughts?

Cheers,
Simon

**Comment by parente** [comment]
Turning off the token check for OPTIONS sounds right to me. Feel free to submit a PR if you'd like. Thanks for reporting this.

**Comment by rolweber** [comment]
Background information for those not familiar with the CORS protocol:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS#Overview
https://fetch.spec.whatwg.org/#cors-preflight-request

**Comment by SimonBiggs** [comment]
Created a pull request over at:
https://github.com/jupyter/kernel_gateway/pull/258

**Comment by parente** [comment]
Fixed by #258.

**Comment by SimonBiggs** [comment]
@parente would a 2.0.1.dev0 release be able to be pushed to pypi? If I remember correctly users don't default to upgrading to dev releases, but I would be able to pin a version number in my own setup.py.

**Comment by parente** [comment]
I'll work on a 2.0.1 changelog PR and release today.

**Comment by parente** [comment]
https://pypi.org/project/jupyter_kernel_gateway/2.0.1/
https://github.com/conda-forge/jupyter_kernel_gateway-feedstock/pull/7

**Comment by SimonBiggs** [comment]
Brilliant :). Thank you, thank you :)
