### ISSUE TITLE
400 GET error when trying websocket

### ISSUE THREAD

**Issue by tanguycdls** [jupyter/kernel_gateway#261]
Hi, I'm trying to create a connection between a distant kernel running Kernel Gateway and an angular App. I manage to create kernel easily using POST request but I can't get a WebSocket connection. 
I try to get using : 
`this.http.get('*****/api/kernels/ff826459-8120-4245-9222-3901df09fa26/channels?token=test').subscribe(data => {
      // Read the result field from the JSON response.
      console.log(data)
    });`
On the server I get a 400 Error and a Warning for 
`
[KernelGatewayApp] WARNING | No session ID specified
[KernelGatewayApp] Adapting to protocol v5.1 for kernel ff826459-8120-4245-9222-3901df09fa26
`
Do you know what i am doing wrong ? 
Thank you !

**Comment by rolweber** [comment]
I'm not familiar with angular apps. But `http.get` looks like it would send a GET request, rather than open a websocket connection.

I've been using https://github.com/jupyterlab/services for connecting to kernels. Just noticed that the library has moved though. Maybe you can use its replacement in your app? That would shield you from some of the Jupyter internals.

**Comment by tanguycdls** [comment]
Thank you for your answer, I thought we needed to Get and then treat the result as a ws connection.

I tried to use JupyterLabservices this morning but the example given in Node does not work for me. I use a distant kernel in an EC2 instance and I could not make it work even while just retrieving kernels ids. Maybe I don't use it correctly, do you know where to get more example ? 

Thank you again for your help

**Comment by SimonBiggs** [comment]
I am in the process of  writing an angular app that talks to the kernel
gateway/notebook server.

It's a work in progress but the connections work.

The angular part can be found here:
https://github.com/SimonBiggs/quarc-services

The notebook/gateway wrapper here:
https://github.com/SimonBiggs/quarc

I distilled the key parts of the connection into an example. Probably best
start with this example, if you want to see how I built it in to the rest
have a look at what I was doing above:
https://github.com/jupyterlab/jupyterlab/tree/master/packages/services/examples/typescript-browser-with-output

If you want to see a bit more with angular and jupyter I am building a
jupyterlab extension that uses Angular over here:
https://github.com/SimonBiggs/jupyterlab-form

**Comment by tanguycdls** [comment]
Thank you @SimonBiggs, I'll try to use your code ! You said talks to the kernel gateway / notebook is it basically the same thing to do both or the API's are different ? 

Thank's!

**Comment by SimonBiggs** [comment]
Should be the same.

**Comment by SimonBiggs** [comment]
Also, if it helps, the real meat of my connection within my Angular app is done by "KernelService":
https://github.com/SimonBiggs/quarc-services/blob/master/src/app/scripted-forms/kernel.service.ts

**Comment by SimonBiggs** [comment]
@tanguycdls how'd you go?

**Comment by tanguycdls** [comment]
Thank's to ask @SimonBiggs ! I used you kernel.service as a basis to understand how it would work. Now I can create /close/list all kernels in the angular app. I also managed to make a text area to send code to the kernel and see the result. I tried to use codemirror but i could not make it work so I use ace editor with python mode. What I wanted at the beginning of the project was a notebook style interface but a simple code area can make it as well... 
What I'm trying to do now is to open .py file in the code editor and improve the code completion of ace (I would like to add the auto completion for the modules installed with the kernel like tensorflow).
The aim of the project is to provide a light python IDE to use on an instance with GPUs. The web client communicates directly to the instance with kernel gateway and send code there. The files that are needed are sent independently. 

Thank's again for your help and I will try to write down all of this at the end it could be helpful for some people like me...

**Comment by SimonBiggs** [comment]
A lot of the tooling you're after is built into jupyterlab. Have you considered creating a jupyterlab extension? I started out building a stand alone web app with angular but then decided to take the jump and learn to build a jupyterlab extension. Given that I could embed angular within the extension I didn't lose what I had already done.

Now that I'm an extension plugging into jupyterlab tasks such as file loading, saving, and others have become a lot quicker to implement.

**Comment by tanguycdls** [comment]
Yes thanks, ,this morning I tried to use the editor example in Jupyterlab/jupyterlab but my knowledge in typescript/ angular is pretty limited so I gave up rapidly.
I didn't know the concept of the extension in JupyterLab, it looks really nice. I think I will try to give it a more serious look in the following days and try to create one.
But can jupyterlab work like jupyter with kernel gateway in remote ? 
Anyway the functionality of jupyterlab looks really promising !

**Comment by SimonBiggs** [comment]
I'm pretty sure it's possible. But it wouldn't be a plug and play method. You'd have to dig into the code and have a custom wrapper that starts the thing up. I'd be happy to work it out with you if you wanted to give it a try.

**Comment by tanguycdls** [comment]
Thank's but I think i wont have the time to try, I mostly needed request code to work and even if it's not perfect it works :) ... 
I still have some issue understanding how to set the headers so that the token auth works? 
Right now I had removed all the security using these parameters:
 jupyter kernelgateway --KernelGatewayApp.port=8889 --KernelGatewayApp.ip=* --KernelGatewayApp.allow_origin='*' --JupyterWebsocketPersonality.list_kernels=True --JupyterWebsocketPersonality.list_kernels=True --KernelGatewayApp.allow_credentials='true' --KernelGatewayApp.allow_headers='X-XSRFToken,accept , Content-Type' --KernelGatewayApp.allow_methods='GET,POST,DELETE,OPTIONS'
But now I would like to add at least a security token and if I can use https, I don't understand what Headers I need to put to use https and pass the token ? 
If you want I can open a new issue if you prefer? 
Thank you !

**Comment by SimonBiggs** [comment]
The following link is to my code when I was using kernel gateway app before
I swapped to the notebook server:

https://github.com/SimonBiggs/quarc/blob/794d3f168f5b95bd27849a8e199b5399c2c2c3f6/quarc/quarc.py#L105&113

It's using https, and tokens.

**Comment by SimonBiggs** [comment]
To use https you're probably best familiarising yourself with let's encrypt:
https://letsencrypt.org/

**Comment by SimonBiggs** [comment]
Also do make a new issue, just so that if future people Google search your
question they'll be pointed in the right direction...

**Comment by parente** [comment]
Thanks for the info @SimonBiggs. I'm going to close this issue out as resolved. @tanguycdls feel free to open that other ticket mentioned.

**Comment by SimonBiggs** [comment]
You're welcome :). My pleasure :).
