### ISSUE TITLE
Make KernelSpecManager and KernelManager configurable

### ISSUE THREAD

**Issue by shiti-saxena** [jupyter/kernel_gateway#265]
We want to make KernelSpecManager and kernel_manager_class configurable at run-time. This gives users flexibility to customize how Kernelspecs are fetched and how kernels are started.

**Comment by rolweber** [comment]
Seems appropriate for websockets mode.

I wonder how this interacts with the notebook-http mode, where only a single kernel is started at the time the kernel gateway itself starts up. It makes sense to have a configurable KernelSpecManager there, yes. But replacing the kernel manager seems odd in that mode.

**Comment by shiti-saxena** [comment]
These changes simplify running Kernel Gateway through app orchestration framework such as Docker/Kubernetes. 
The notebook-http mode also starts a kernel and if users want to customize how that kernel is started/ stopped they will need to be able to do so by configuring the KernelManager.
