### ISSUE TITLE
can kernel gateway import module from local file?

### ISSUE THREAD

**Issue by jarrekk** [jupyter/kernel_gateway#267]
Now I use jupyter notebook to test python coding and I can use kernel gateway to export some data, but I want to write some code snippet at another, so my directory structure will be this:
![image](https://user-images.githubusercontent.com/10969478/32255886-8cf1be7e-be79-11e7-9fc9-fbd1b7d80421.png)
in jupyter notebook it works ok:
![image](https://user-images.githubusercontent.com/10969478/32255775-d54b4bb4-be78-11e7-9fd5-3fb20d821af6.png)
but when I run `jupyter kernelgateway --config='./jupyter_kernel_gateway_config.py'`, something error, it shows utils can't be imported.

```
➜ jupyter kernelgateway --config='./jupyter_kernel_gateway_config.py'
[KernelGatewayApp] Kernel started: e8a46b44-6372-4104-8b2e-6f91de2dd8fe
[KernelGatewayApp] Kernel shutdown: e8a46b44-6372-4104-8b2e-6f91de2dd8fe
Traceback (most recent call last):
  File "/Users/jack/.pyenv/py3.6.3/bin/jupyter-kernelgateway", line 11, in <module>
    sys.exit(launch_instance())
  File "/Users/jack/.pyenv/py3.6.3/lib/python3.6/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/Users/jack/.pyenv/py3.6.3/lib/python3.6/site-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "/Users/jack/.pyenv/py3.6.3/lib/python3.6/site-packages/kernel_gateway/gatewayapp.py", line 343, in initialize
    self.init_configurables()
  File "/Users/jack/.pyenv/py3.6.3/lib/python3.6/site-packages/kernel_gateway/gatewayapp.py", line 393, in init_configurables
    self.personality.init_configurables()
  File "/Users/jack/.pyenv/py3.6.3/lib/python3.6/site-packages/kernel_gateway/notebook_http/__init__.py", line 78, in init_configurables
    self.parent.kernel_manager
  File "/Users/jack/.pyenv/py3.6.3/lib/python3.6/site-packages/kernel_gateway/services/kernels/pool.py", line 68, in __init__
    super(ManagedKernelPool, self).__init__(prespawn_count, kernel_manager)
  File "/Users/jack/.pyenv/py3.6.3/lib/python3.6/site-packages/kernel_gateway/services/kernels/pool.py", line 30, in __init__
    self.kernel_manager.start_seeded_kernel()
  File "/Users/jack/.pyenv/py3.6.3/lib/python3.6/site-packages/kernel_gateway/services/kernels/manager.py", line 72, in start_seeded_kernel
    return ioloop.IOLoop.current().run_sync(start)
  File "/Users/jack/.pyenv/py3.6.3/lib/python3.6/site-packages/tornado/ioloop.py", line 458, in run_sync
    return future_cell[0].result()
  File "/Users/jack/.pyenv/py3.6.3/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/Users/jack/.pyenv/py3.6.3/lib/python3.6/site-packages/tornado/gen.py", line 1069, in run
    yielded = self.gen.send(value)
  File "/Users/jack/.pyenv/py3.6.3/lib/python3.6/site-packages/kernel_gateway/services/kernels/manager.py", line 109, in start_kernel
    raise RuntimeError('Error seeding kernel memory', msg['content'])
RuntimeError: ('Error seeding kernel memory', {'status': 'error', 'traceback': ['\x1b[0;31m---------------------------------------------------------------------------\x1b[0m', '\x1b[0;31mModuleNotFoundError\x1b[0m                       Traceback (most recent call last)', '\x1b[0;32m<ipython-input-1-cda732ff3fdd>\x1b[0m in \x1b[0;36m<module>\x1b[0;34m()\x1b[0m\n\x1b[1;32m      1\x1b[0m \x1b[0;32mimport\x1b[0m \x1b[0mmath\x1b[0m\x1b[0;34m\x1b[0m\x1b[0m\n\x1b[1;32m      2\x1b[0m \x1b[0;32mimport\x1b[0m \x1b[0mjson\x1b[0m\x1b[0;34m\x1b[0m\x1b[0m\n\x1b[0;32m----> 3\x1b[0;31m \x1b[0;32mfrom\x1b[0m \x1b[0;34m.\x1b[0m\x1b[0mutils\x1b[0m\x1b[0;34m.\x1b[0m\x1b[0mpg\x1b[0m \x1b[0;32mimport\x1b[0m \x1b[0mconn_pg\x1b[0m\x1b[0;34m\x1b[0m\x1b[0m\n\x1b[0m\x1b[1;32m      4\x1b[0m \x1b[0;32mfrom\x1b[0m \x1b[0;34m.\x1b[0m\x1b[0mutils\x1b[0m\x1b[0;34m.\x1b[0m\x1b[0mchart\x1b[0m \x1b[0;32mimport\x1b[0m \x1b[0mplotBarAndLine\x1b[0m\x1b[0;34m\x1b[0m\x1b[0m\n\x1b[1;32m      5\x1b[0m \x1b[0;32mimport\x1b[0m \x1b[0mpandas\x1b[0m\x1b[0;34m\x1b[0m\x1b[0m\n', "\x1b[0;31mModuleNotFoundError\x1b[0m: No module named '__main__.utils'; '__main__' is not a package"], 'ename': 'ModuleNotFoundError', 'evalue': "No module named '__main__.utils'; '__main__' is not a package", 'engine_info': {'engine_uuid': 'b4814f5b-afd1-4823-9f3f-af32348d5017', 'engine_id': -1, 'method': 'execute'}, 'execution_count': 1, 'user_expressions': {}, 'payload': []})
```

**Comment by rolweber** [comment]
Local imports are relative to the current working directory. Either start the kernel gateway from the `notebook` directory, or `!cd <wherever>/notebook` in your notebook before importing, or copy the `utils` directory tree to the directory from which you are starting the kernel gateway.

**Comment by parente** [comment]
The `from .utils.pg import pg` syntax only works when a module in a package imports another module from the package. The kernel executing the notebook is `__main__` and so the relative package resolution will not work.

Either install the `utils` package separately in the same virtual / conda environment as the kernel_gateway or use `from utils import pg` syntax (no dot).

**Comment by jarrekk** [comment]
@rolweber @parente 
![image](https://user-images.githubusercontent.com/10969478/32705864-37e13180-c7de-11e7-8f4a-d958ff76fb35.png)
`api.ipynb` and `notebook.ipynb` and `utils` are at same folder(notebook) and I tried both `from .utils.pg import Postgresql` and `from utils.pg import Postgresql`, the same error.😑

@parente another method:
> install the utils package separately in the same virtual / conda environment 

It can works since use **pip** install libraries can work, but seems not convenient.

**Comment by parente** [comment]
@rolweber has it right: the kernel's current working directory is wherever you start the kernel gateway server. Are you running the command from within the `notebook` directory, then seeing an error with `from utils import pg`?

**Comment by jarrekk** [comment]
@parente jupyter notebook doesn't show this error.

**Comment by rolweber** [comment]
It seems this discussion has ended. Python module import depends on Python path settings, and local imports also on the current working directory. Details have to be figured out case by case. This is not a problem that needs fixing in KG.
