### ISSUE TITLE
Differences between Jupyter Kernel Gateway and Jupyter Notebook server

### ISSUE THREAD

**Issue by barrachri** [jupyter/kernel_gateway#268]
I started to play with jupyter kernel gateway.

Considering a use case where you connect to the kernel using nteract or hydrogen, with a remote kernel.
What would be the main difference between a classic jupyter-notebook and using the jupyter kernel gateway?

For now the only thing I need to specify is the given token (with the jupyter notebook).

A part for the http-mode the rest seems very similar, am I correct?

**Comment by rolweber** [comment]
I know neither nteract nor hydrogen, so I can only comment in general. The Kernel Gateway in websocket mode is basically a subset of a plain Jupyter Notebook server. The APIs dealing with notebooks are missing, the APIs dealing with kernels and sessions are the same. Of course, the Kernel Gateway doesn't have a UI either.

**Comment by maxim-lian** [comment]
I had the same questions; there's some discussion here: https://github.com/nteract/hydrogen/pull/1079

In brief - the vision of the kernel gateway vision is compelling, but given the current state of the code: use the notebook server

**Comment by barrachri** [comment]
Thanks @maxim-lian, the discussion answers a lot of questions!

**Comment by kevin-bates** [comment]
Discussion appears complete - closing.
