### ISSUE TITLE
kernel_gateway.notebook_http not found when running Jupyter Kernel Gateway inside Docker container

### ISSUE THREAD

**Issue by WorldofDataScience** [jupyter/kernel_gateway#273]
Details here: 
https://stackoverflow.com/questions/48086434/kernel-gateway-notebook-http-not-found-when-running-jupyter-kernel-gateway-insid

**Comment by kevin-bates** [comment]
@WorldofDataScience - Looks like you're missing the trailing single-quote on the api parameter of the docker CMD: `"--KernelGatewayApp.api='kernel_gateway.notebook_http"`.

**Comment by WorldofDataScience** [comment]
Oops. That was dumb. Thanks! :)

**Comment by SweetLunar** [comment]
I made end-point by kernel gateway but nothing appears in the browser just i can see {"reason": "Not Found", "message": ""} message. I checked that the python code is working well at the cell which including # GET command in the notebook script. Why is my kernel browser not working? T.T

**Comment by rolweber** [comment]
@SweetLunar Please open a separate issue for your problem, instead of commenting on an issue that is already closed.

Also, we will need more information about your setup and configuration, and the URL you are calling.
