### ISSUE TITLE
how to get service  deployed by kernel gateway using jupyterhub

### ISSUE THREAD

**Issue by xuande** [jupyter/kernel_gateway#274]
I achieved multi-user management using jupyterhub + docker spawner + oauth， and I want to add a kernel gateway for every user, then how should I configure jupyterhub to visit the service deployed by kernel gateway through https://ip:port/user/jovyan/**

**Comment by parente** [comment]
I think JupyterHub 0.8 has support for multiple servers per user. From the release notes:

> There is preliminary support for multiple (named) servers per user in the REST API. Named servers can be created via API requests, but there is currently no UI for managing them.

I have personally tried this feature yet. Maybe @willingc or @minrk can point to an example?

**Comment by rolweber** [comment]
I'm not sure what the point is of running a kernel gateway (in websocket mode, I assume?) alongside a notebook server. The notebook server already provides the APIs for managing kernels without notebooks.

Anyway, you're far more likely to get answers regarding JupyterHub configuration if you post them to JupyterHub.
