### ISSUE TITLE
How to get port that the kernel gateway is running via code

### ISSUE THREAD

**Issue by orobsonpires** [jupyter/kernel_gateway#276]
Hi All,

I have an application which executes the following command:

"jupyter kernelgateway --api='kernel_gateway.notebook_http' --port=15000 --seed_uri='x'"

However, if the port 15000 is already in use the application will take the next port available. I would to be able to detect this port after executing this command. Is that possible via code?

**Comment by parente** [comment]
The kernel gateway uses the same free-port seeking code as Jupyter Notebook. The final port selected is only emitted in the logs at the moment. 

Jupyter Notebook also creates a JSON file that lives under the Jupyter runtime directory, retrievable by running `jupyter --runtime-dir` in the shell or using the `jupyter_core` Python package. The JSON file will be named `nbserver-<pid of the notebook server>.json`. Either KG does not inherit this behavior or doesn't have it enabled.

**Comment by rolweber** [comment]
Add another parameter to your command: `--port_retries=0`
Then Jupyter will fail to start if the port is busy, and you can select a different port for a retry.

That option was introduced specifically for your situation, see ipython/ipython#1750.

http://jupyter-kernel-gateway.readthedocs.io/en/latest/config-options.html

**Comment by orobsonpires** [comment]
Hi guys,

Thank you all for your thoughts! I implemented in that way:

First, I check the availability of the port before calling the command inside of code, if the port is busy I just try the next one until find a free port. Then i connected in this port, and already have the port saved, so is not a problem afterward to use this value.
