### ISSUE TITLE
KeyError when starting server

### ISSUE THREAD

**Issue by CarlCochran** [jupyter/kernel_gateway#277]
I've built the developer setup of the Jupyter Kernel Gateway (master branch) into an Ubuntu 14.04 docker container, and so far have not made any changes. I've installed the Julia 0.4.7 kernel and connected it using IJulia. I have generated the config file with these settings:
```
c.KernelGatewayApp.ip = '*'
c.KernelGatewayApp.port = 8445
c.KernelGatewayApp.api = 'kernel_gateway.notebook_http'
c.NotebookHTTPPersonality.cell_parser = 'kernel_gateway.notebook_http.cell.parser'
c.KernelGatewayApp.seed_uri = 'mynotebook.ipynb'
```
When I launch the gateway server, I get this:
```
ubuntu@bb96347f6951:~$ jupyter kernelgateway
[KernelGatewayApp] Kernel started: 765c4f4f-9543-457f-9d0e-378b0ef80c6b
Starting kernel event loops.
create_request_handlers
[KernelGatewayApp] Registering resource: /widget1, methods: (['POST', 'GET'])
[KernelGatewayApp] Registering resource: /widget2, methods: (['POST', 'GET'])
[KernelGatewayApp] Registering resource: /_api/spec/swagger.json, methods: (GET)
[KernelGatewayApp] Jupyter Kernel Gateway at http://*:8445
ERROR:tornado.general:Uncaught exception, closing connection.
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/zmq/eventloop/zmqstream.py", line 414, in _run_callback
    callback(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/ubuntu/kernel_gateway/kernel_gateway/services/kernels/pool.py", line 145, in <lambda>
    return lambda msg_list: self._on_reply(kernel_id, session, msg_list)
  File "/home/ubuntu/kernel_gateway/kernel_gateway/services/kernels/pool.py", line 124, in _on_reply
    self.on_recv_funcs[kernel_id](msg)
KeyError: '765c4f4f-9543-457f-9d0e-378b0ef80c6b'
```
Any ideas what's going on? Any other info needed?

**Comment by rolweber** [comment]
I'm not familiar with the notebook personality. But from scanning the code, it looks as if [`on_recv_funcs`](https://github.com/jupyter/kernel_gateway/blob/master/kernel_gateway/services/kernels/pool.py#L71) doesn't contain a function for your kernel. This function is usually provided by the [`execute_code`](https://github.com/jupyter/kernel_gateway/blob/master/kernel_gateway/notebook_http/handlers.py#L157) function. But you're seeing the problem on startup, without executing code.

Wild guess: The Julia kernel might send an iopub message on startup, whereas the KG notebook personality expects such messages only in response to code execution requests.

If that guess is correct, it might suffice to add a check in [_on_reply](https://github.com/jupyter/kernel_gateway/blob/master/kernel_gateway/services/kernels/pool.py#L111) like this:
```python
def _on_reply(self, kernel_id, session, msg_list):
    """..."""
    if not kernel_id in self.on_recv_funcs:
        return
    idents, msg_list = ... # rest of the function
```

Would you want to give it a try, and submit a PR if this works?

**Comment by CarlCochran** [comment]
So far it works exactly as you've suggested, thank you!  I need to familiarize myself with how to write a test for it (and how to run the other tests) before I can submit a PR, so I'll get to that soon.
