### ISSUE TITLE
Connect to existing kernel

### ISSUE THREAD

**Issue by Akaban** [jupyter/kernel_gateway#289]
Hi,

It does not seem like we can connect to a kernel launched remotely via kernel_gateway, the jupyter server does not see any kernels launched remotely. Is there a way to do this or is this feature planned in the project? It would be the best thing ever !

Cheers,

Akaban

**Comment by rolweber** [comment]
JKG in websocket-http mode is meant to _provide_ the remote endpoint.
See the nb2kg project for the caller side: https://github.com/jupyter-incubator/nb2kg

**Comment by kevin-bates** [comment]
@Akaban If you're looking for a way to distribute *kernels* across a cluster (and remote from the gateway), while having the notebooks themselves remote on the front side (via nb2kg as Roland mentions), then you'll want to check out [Jupyter Enterprise Gateway](https://github.com/jupyter-incubator/enterprise_gateway) - that's what it does (while deriving directly from JKG).

**Comment by Akaban** [comment]
Hello,

Thank for the answer ! Indeed I misunderstood some parts. Everything's clear now, I'm closing !

Cheers !
