### ISSUE TITLE
Release 2.1.0

### ISSUE THREAD

**Issue by kevin-bates** [jupyter/kernel_gateway#300]
Since it's been 9 months since the last release and with JupyterCon approaching, it seems like a good time to issue a release.  I'm happy to put this together but wanted to get _buy-in_ from others.  We currently have [10 closed PRs](https://github.com/jupyter/kernel_gateway/pulls?utf8=%E2%9C%93&q=is%3Apr+closed%3A%3E2017-11-11+) that would comprise the release.  

The reason for making this a minor release, instead of a patch release, was suggested by @parente due to the dependency updates in #292.  In addition, the changes to Notebook 5.6.0 (with its security update), warrant the delivery of #294 - otherwise JKG falls on its face if users have installed NB 5.6.

TODOs:
- [x] Issue #295.  Since Travis no longer supports Python 3.3 (per update in #293), do we replace 3.3 with 3.7 support?  Last update in #295 is that it doesn't appear Travis is ready with 3.7, so I'm inclined to move forward w/o official 3.7 support.
- [x] Update the changelog both in the project root and doc
- [x] Make a pass through open issues/PRs to see what can be closed (#299 ?)
- [x] Merge #301
- [x] Make @lresende  and @kevin-bates maintainers on pypi
- [x] Follow http://jupyter-dashboards-layout.readthedocs.io/en/latest/maintenance.html#make-a-release process to branch, version bump, tag a release and push to pypi
- [x] Update conda-forge package https://github.com/conda-forge/jupyter_kernel_gateway-feedstock
- [x] Announce release on the jupyter google group (look for past announcements for a template)

Other items?

cc: @parente @rolweber @lresende

**Comment by parente** [comment]
Updated the todo list and checked off one item. I'll keep an eye on this issue. Thanks for working on this @kevin-bates

**Comment by rolweber** [comment]
+1 Makes sense to cut a new release.

**Comment by rolweber** [comment]
I'm OK with not officially supporting Python 3.7 for now. If it works, fine. If it doesn't, we'll accept patches regardless of whether Travis supports 3.7 or not.

**Comment by rolweber** [comment]
Please merge #301 before the release. That was a to-do on my whiteboard for months. Sorry for not getting around to it earlier.

**Comment by kevin-bates** [comment]
@parente - It doesn't look like I have write access on conda-forge to merge the auto-generated PR: https://github.com/conda-forge/jupyter_kernel_gateway-feedstock/pull/10

cc: @lresende

**Comment by parente** [comment]
@kevin-bates I merged the PR there. Can you submit a separate PR adding yourself and @lresende to the maintainers section in the meta.yaml? Once that merges, you should have merge permissions for that repo on conda-forge.

(I didn't want to delay the release and rebuild by asking you to do it in the 2.1.0 PR.)

**Comment by kevin-bates** [comment]
@parente - perfect - thank you!

**Comment by kevin-bates** [comment]
Announcement posted: https://groups.google.com/forum/#!topic/jupyter/5L-V4Bqfd_8

Closing issue.
