### ISSUE TITLE
Would it be possible to automatically expose ipywidgets?

### ISSUE THREAD

**Issue by chmduquesne** [jupyter/kernel_gateway#302]
Hi,

I was wondering if it would be possible to expose all the widgets of a notebook through an automatically generated http resource.

One would then write some js glue so that a static html notebook created with nbconvert would be able to connect to a live notebook.

The same would be needed in order to expose output areas, so they would be connected to their static counterparts, also via some js.

My goal is to automatically export a dashboard, without having to expose the code of the cells.

Here I am only asking whether this would be _possible_. Any opinion?

Cheers!

**Comment by parente** [comment]
Hi @chmduquesne. @SylvainCorlay and @maartenbreddels presented almost exactly what you are described at JupyterCon just last week in their talk about ipywidgets. They demoed a tool, called voilà, which I believe they plan to open source.

**Comment by chmduquesne** [comment]
@SylvainCorlay @maartenbreddels I would be very interested in knowing more about this. Any way to learn more?

**Comment by maartenbreddels** [comment]
voila currently takes a notebook as argument, on a http get it will spin up a kernel, run nbconvert with that kernel and keep the kernel alive. The html from nbconvert gets send to the browser, and the client connects to that kernel, the comms get created so all widgets work. Voila builds on jupyter_server (a stripped down server of notebook), but does not allow arbitrary code execution.
A gif is worth a `nr_of_frames * 1000` words:
![voila-demo](https://user-images.githubusercontent.com/1765949/44866432-84984680-ac85-11e8-84ff-83f8b433f29d.gif)
The repo is not still private, but my best guess is that it will be released 'soon', don't hold your breath though :)

**Comment by chmduquesne** [comment]
@maartenbreddels thank you very much! this is exactly what I wanted, functionally: exporting my notebook so that the controls are still functional, but where it is no longer possible to execute arbitrary python code.

Any reason why you guys are currently keeping it private? If your code needs improvement, I'd be happy to help. Of course if it's about cleaning up private stuff, I understand, though :-)

**Comment by cbcunc** [comment]
@maartenbreddels, sweet!

**Comment by SylvainCorlay** [comment]
> Any reason why you guys are currently keeping it private? If your code needs improvement, I'd be happy to help. Of course if it's about cleaning up private stuff, I understand, though :-)

voila requires the master branch of `nbconvert` and is also based on `jupyter_server`. No secret sauce here. We just thought we would push it out once it is in a better state. I am off for a couple of days, and will make the `voila` repository public when I am back :)

**Comment by chmduquesne** [comment]
Sounds also reasonable :-)

I am very looking forward to have a look at the code and try it out!

**Comment by kevin-bates** [comment]
This looks sufficiently discussed and probably belongs in a different repo anyway - closing.
