### ISSUE TITLE
Way to define Parameters in HTTP Notebook Swagger 

### ISSUE THREAD

**Issue by fullstackwebdev** [jupyter/kernel_gateway#326]
from https://jupyter-kernel-gateway.readthedocs.io/en/latest/http-mode.html

_The resource /_api/spec/swagger.json is automatically generated from the notebook used to define the HTTP API. The response is a simple Swagger spec which can be used with the Swagger editor, a Swagger ui, or with any other Swagger-aware tool._

I was able to get the Notebook HTTP mode and get the swagger spec, but I was wondering if there was a way to set the parameters in addition to the endpoints? Right now, all I can see is the actually resources but my SwaggerUI doesn't give me the parameters.

I can vaguely make out this feature might be in here but not documented from this area of the code: 
https://github.com/jupyter/kernel_gateway/blob/master/kernel_gateway/notebook_http/swagger/parser.py#L27

Can I simply set more properties? Is there any examples or documentation on the format? 

thanks

Wonderful project, looks like an incredible amount of hard work went into this. Thanks

**Comment by kevin-bates** [comment]
Hi @fullstackwebdev - I'm afraid that what you see is all there is.  I'm not able to find any additional information relative to swagger generation from the seed notebook.  Should you have success reverse engineering things we would absolutely welcome doc and/or code contributions - thank you.

**Comment by fullstackwebdev** [comment]
thanks, I appreciate the response!
