### ISSUE TITLE
Kernel gateway asks for PEM pass phase on every API request

### ISSUE THREAD

**Issue by phpmaps** [jupyter/kernel_gateway#330]
Is there a way to start a Kernel Gateway so that SSL requests do not prompt for the private key pass phase in every API request? The prompts will show up in the terminal where the Kernel Gateway was started.

 I was looking for a ```kernelgateway --keyfile_passphase``` but did not see this listed in the documentation.  If I don't create a pass phase when creating the Self Signed files, all is fine (there is no prompt).

To that end, would a certificate issued from a CA authority make a difference?  Would that look like:

```jupyter kernelgateway --KernelGatewayApp.ip=0.0.0.0 --KernelGatewayApp.port=9999 --KernelGatewayApp.allow_origin='*' --client-ca=../certs/<ca_cert_name>.crt ```

Note, no --certfile and --keyfile argument above.

 At the end of the day I would like to use the Kernel Gateway without pass phase prompts.  Any help / thoughts would be appreciated, as I am not sure on what would be the best approach.

**Comment by rolweber** [comment]
You shouldn't specify a passphrase for the private key for the server. No, there are no provisions for specifying a passphrase in the config. If you consider the key so sensitive that it needs to be protected by a passphrase, you wouldn't want the passphrase to be stored in memory and a config file either - or to appear in the process list when you pass it as a command-line argument.

If you don't specify certfile and keyfile, then the server will not run with TLS. The client-ca is for outbound TLS connections, not for incoming ones.

**Comment by phpmaps** [comment]
@rolweber thanks for the fast response.  It's very helpful knowing the current options.   Let me digest.   In my head I was thinking that in process may be reasonable.

**Comment by rolweber** [comment]
Passphrases are useful to protect your private keys on the client side, for example if you use them to sign mails or authenticate with a browser. But server components like JKG are meant to run unattended, so there's no user who could enter the passphrase when the server needs to be (re)started. If you have to store the passphrase on the same system where the private key is stored, there's no security gained by having the passphrase at all.

**Comment by phpmaps** [comment]
@rolweber Great.  This pattern is similar to other systems I've worked with, but in AWS.   Thanks again for sharing your comments.  I will close the issue.
