### ISSUE TITLE
specifying the gateway-url from console

### ISSUE THREAD

**Issue by mahdi-b** [jupyter/kernel_gateway#335]
I can successfully use a gateway server for kernel management with Jupyter notebook by starting the notebook with the `gatway-url` option. Is it possible to do the same thing with `jupyter console`?

Thank you,

Mahdi

**Comment by kevin-bates** [comment]
No.  Having just looked at [`jupyter console`](https://github.com/jupyter/jupyter_console) it appears to talk to kernels directly and essentially implements its own kernel manager.

`--gateway-url` is intended for notebook servers and instructs the local server's kernel management to be redirected to another "notebook server".  As a result, lots of things would need to happen for jupyter console to get into this game.
