### ISSUE TITLE
Support for extensions in kernel gateway

### ISSUE THREAD

**Issue by AshwinKAshok** [jupyter/kernel_gateway#336]
Is there a way to use extensions like NBResuse in kernel gateway. I would like to use Kernel gateway with NBResuse to get kernel specific metrics.

**Comment by kevin-bates** [comment]
KernelGateway does not have a facility for loading notebook server extensions.  In addition, it's a headless server, so, unless you "plumb" the `/metrics` endpoint similar to what NB2KG (or notebook.gateway) does for kernel management, you won't be able to leverage the notebook (UI) extensions from the Notebook UI.

It would be much better to include metrics in the kernel activity tracking, which could then be obtained via the `/api/kernels/{kernel_id}` endpoint and just work - regardless of whether a gateway was configured or not.
