### ISSUE TITLE
Improve the doc formating on RTD

### ISSUE THREAD

**Issue by mwouts** [jupyter/kernel_gateway#344]
Hi,

Thanks for this nice project!

I see that the documentation uses Markdown files, but these files are not properly rendered on RTD.

For instance, this file: https://github.com/jupyter/kernel_gateway/blob/master/docs/source/features.md
![image](https://user-images.githubusercontent.com/29915202/94289969-d6415700-ff59-11ea-880d-40ba58a100d6.png)

is rendered on https://jupyter-kernel-gateway.readthedocs.io/en/latest/features.html as
![image](https://user-images.githubusercontent.com/29915202/94289988-e0fbec00-ff59-11ea-8ba4-77d1ad27322c.png)

In my experience this can be fixed by activating the `recommonmark` extension in `docs\conf.py`.

Would you be open to a PR going into that direction?

**Comment by kevin-bates** [comment]
Absolutely!  Thank you Marc!

**Comment by mwouts** [comment]
Done! And that is possibly the shortest PR I ever made :smile: 
Thank you Kevin for you quick answer.
