### ISSUE TITLE
Live reload of gateway on file change

### ISSUE THREAD

**Issue by itproto** [jupyter/kernel_gateway#350]
Is it some way to update kernel gateway REST service after updating target .ipynb

I am running docker container with the following entrypoint `ENTRYPOINT ["tini", "--", "/docker-entrypoint.sh"]`
```
start-notebook.sh --NotebookApp.port=9999 --NotebookApp.notebook_dir=/srv/notebooks/ &
jupyter kernelgateway --KernelGatewayApp.port=7777 --KernelGatewayApp.api=notebook-http --KernelGatewayApp.ip=0.0.0.0 --KernelGatewayApp.seed_uri=/srv/notebooks/hello.ipynb
e
```
I want to run both processes at the same time. I can access and edit the target hello.ipynb , but rest API never reflects changes (until container restart).

Is it possible to "live-reload" gateway on file change?

**Comment by kevin-bates** [comment]
This capability doesn't exist today.  I added [_dynamic configuration support_](https://github.com/jupyter/enterprise_gateway/pull/748) to Enterprise Gateway at an experimental level that could probably be leveraged here.  It would require that `seed_uri` be configured via a configuration file (which would need to be mounted into the container) and you'd probably need to add an `observe` trait to force JKG to re-populate its use of the notebook.

I'm not very familiar with the http-personality and don't know if this kind of "reset" is possible w/o restarting the server though - so you'd need to experiment with it.

Just some thoughts.

**Comment by itproto** [comment]
Kevin, thank you for your thoughts. That is very insightful
