### ISSUE TITLE
local notebook file with URL characters in path break loading

### ISSUE THREAD

**Issue by bgerrity** [jupyter/kernel_gateway#352]
https://github.com/jupyter/kernel_gateway/blob/7636f219d74309d7888096ef1cedc32eec73655d/kernel_gateway/gatewayapp.py#L352-L375

Special characters can be valid unix filenames; `KernelGatewayApp._load_notebook` incorrectly handles cases where they are used, effectively dropping part of a path.

e.g. `/foo/bar/weird?notebook#name` would be opened as `/foo/bar/weird` despite `weird?notebook#name` being the file's correct name.

**Comment by kevin-bates** [comment]
Fixed via #353
