### ISSUE TITLE
Invalid Options Should Terminate App

### ISSUE THREAD

**Issue by Lull3rSkat3r** [jupyter/kernel_gateway#36]
It would be helpful if the application would terminate when receiving invalid command line args. For example, I sent `--KernelGatewatApp.api` instead of `--KernelGatewayApp.api`. This will help user error when deploying kernel gateway.

**Comment by parente** [comment]
This is handled by (or not handled by) the ancestor classes. I bet their default behavior is to pass through anything because there might be a class not yet loaded that wants to receive the config values. We'll have to see if there's a way to fail-fast.

**Comment by Lull3rSkat3r** [comment]
Looked around through the traitlet source and docs to see if there was anything we could do. We did not find anything obvious. I posted an issue, ipython/traitlets#145, with the traitlets repo to see if there is anything they support.

**Comment by parente** [comment]
Bumping out of 0.2.0 for now.

**Comment by parente** [comment]
I'm not sure there's much we can do on this one, especially now that we support api/personality plug-ins from arbitrary Python packages. The list of classes and their traitlets is never known up-front.

I think we can close. If traitlets, notebook, or other Jupyter projects find a nice solution, we'll adopt it.
