### ISSUE TITLE
kernel_gateway incompatible with Jupyter API?

### ISSUE THREAD

**Issue by crossvalidator** [jupyter/kernel_gateway#362]
Hello, I am using kernel_gateway latest version 2.5.0

I am using Websocket personality. 

I am able to send code snippets for execution using the API.

But kernel interrupt and restart requests fail. I get this message (truncated to focus on the important part)

```
Uncaught exception OPTIONS /api/kernels/59aa4970-97a2-4bb1-b3e9-f6dd26cb02c6/interrupt

Traceback (most recent call last):
      File "/opt/conda/lib/python3.8/site-packages/tornado/web.py", line 1701, in _execute
        result = method(*self.path_args, **self.path_kwargs)

TypeError: options() got an unexpected keyword argument 'kernel_id'
```
I searched for `kernel_id` in the kernel_gateway codebase. But not sure where this issue is arising from. Looks like kernel_gateway is using `kernel_id` in some request made to Jupyter API and that API has since evolved and doesn't accept this request argument.

Can anyone point me in the right direction here? I am happy to look into this more and  create a pull reuqest if I can fix it.

**Comment by crossvalidator** [comment]
I have gained some more knowledge. 

I looked in `jupyer/notebook` - It has a method `interrupt_kernel` - this method looks like this

```
async def interrupt_kernel(self, kernel_id, **kwargs):
        """Interrupt a kernel by its kernel uuid.

        Parameters
        ==========
        kernel_id : uuid
            The id of the kernel to interrupt.
        """
        kernel_url = self._get_kernel_endpoint_url(kernel_id) + '/interrupt'
        self.log.debug("Request interrupt kernel at: %s", kernel_url)
        response = await gateway_request(
            kernel_url, method='POST', headers={'Content-Type': 'application/json'}, body=json_encode({})
        )
        self.log.debug("Interrupt kernel response: %d %s", response.code, response.reason)
```

This method is invoked in this code in that project

```
class KernelActionHandler(APIHandler):

    @web.authenticated
    @gen.coroutine
    def post(self, kernel_id, action):
        km = self.kernel_manager
        if action == 'interrupt':
            yield maybe_future(km.interrupt_kernel(kernel_id))
            self.set_status(204)
        if action == 'restart':

            try:
                yield maybe_future(km.restart_kernel(kernel_id))
            except Exception as e:
                self.log.error("Exception restarting kernel", exc_info=True)
                self.set_status(500)
            else:
                model = yield maybe_future(km.kernel_model(kernel_id))
                self.write(json.dumps(model, default=date_default))
        self.finish()
```


Clearly, it passes in the `kernel_id` as the first argument. My guess is the code in `kernel_gateway` that invokes this code in the `KernelActionHandler` (or its equivalent repr) is not passing in the `kernel_id` as the first argument. Instead it is passing in the `**kwargs` as named params. 

Haven't been able to identify where this happens in `kernel_gateway` yet.

**Comment by kevin-bates** [comment]
The missing handlers are located in notebook in similar locations. Could you please include the complete traceback that was truncated in the opening description?
I suspect this is occurring at a lower level. Do you see the same traceback for both interrupt and restart attempts? Thanks

**Comment by crossvalidator** [comment]
Thank you for responding quickly. Here are the tracebacks.

For Restart
```
[E 210517 12:04:17 web:1788] Uncaught exception OPTIONS /api/kernels/df589737-757e-4e0e-bd0c-6290a770f270/restart (10.8.5.4)
    HTTPServerRequest(protocol='http', host=REDACTED, method='OPTIONS', uri='/api/kernels/df589737-757e-4e0e-bd0c-6290a770f270/restart', version='HTTP/1.1', remote_ip=REDACTED)
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.8/site-packages/tornado/web.py", line 1701, in _execute
        result = method(*self.path_args, **self.path_kwargs)
    TypeError: options() got an unexpected keyword argument 'kernel_id'
[KernelGatewayApp] WARNING | Unhandled error
[E 210517 12:04:17 web:2246] 500 OPTIONS /api/kernels/df589737-757e-4e0e-bd0c-6290a770f270/restart (10.8.5.4) 1.69ms
```


For interrupt
```
[E 210517 12:06:26 web:1788] Uncaught exception OPTIONS /api/kernels/df589737-757e-4e0e-bd0c-6290a770f270/interrupt (10.8.5.4)
    HTTPServerRequest(protocol='http', host=REDACTED, method='OPTIONS', uri='/api/kernels/df589737-757e-4e0e-bd0c-6290a770f270/interrupt', version='HTTP/1.1', remote_ip=REDACTED)
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.8/site-packages/tornado/web.py", line 1701, in _execute
        result = method(*self.path_args, **self.path_kwargs)
    TypeError: options() got an unexpected keyword argument 'kernel_id'
[KernelGatewayApp] WARNING | Unhandled error
[E 210517 12:06:26 web:2246] 500 OPTIONS /api/kernels/df589737-757e-4e0e-bd0c-6290a770f270/interrupt (10.8.5.4) 1.75ms
```

There is a bit of confusion about what is the correct path for these requests. I am sending them to `/api/kernels/<kernel_id>/interrupt`. But in file located at `jupyter_websocket/swagger.yaml` of `kernel_gateway` project it says the request path is `/kernels/<kernel_id>/interrupt`. I tried that path - it was sending a 404 immediately.

**Comment by kevin-bates** [comment]
Hmm - this is strange.  I'm unable to reproduce this using 2.5.0...
```
[KernelGatewayApp] Kernel interrupted: ab5444f4-c59f-4284-a6b5-774ea8ae986d
[I 210517 07:46:45 web:2250] 204 POST /api/kernels/ab5444f4-c59f-4284-a6b5-774ea8ae986d/interrupt (127.0.0.1) 1.26ms

[KernelGatewayApp] Kernel restarted: ab5444f4-c59f-4284-a6b5-774ea8ae986d
[I 210517 07:47:31 web:2250] 200 POST /api/kernels/ab5444f4-c59f-4284-a6b5-774ea8ae986d/restart (127.0.0.1) 322.62ms
```
This appears to be coming from the tornado code and have run using tornado versions 6.0.4 and 6.1 on Python 3.7.8.

What kind of client are you using - Notebook, Jupyter Lab, ??? - I'm using Jupyter Lab.

Lastly, what version of notebook are using under kernel gateway?  I've tried with both 6.1.1 and 6.4.0.

**Comment by crossvalidator** [comment]
I am using `6.0.4` for `tornado`, and `6.1.4` for `notebook` under `kernel-gateway`. I am basically adding `kernel-gateway` on top of the `jupyter/scipy-notebook` docker image.

I am trying to create a custom front end so my client is just javascript code that I wrote from scratch. May be I made some mistake in querying the `kernel-gateway` api. But the code execution works just fine.

**Comment by kevin-bates** [comment]
Can you please confirm whether you can perform interrupt and restarts using a Notebook or Lab front end?  If so, then I think that would be a good data point that the issue is somewhere in your client somehow.  If you cannot perform the operations with notebook/lab, then that implies there's an environmental issue somewhere.

**Comment by crossvalidator** [comment]
How do I connect a notebook front end to the `kernel-gateway` server? Is there an example where this is done.

**Comment by kevin-bates** [comment]
> How do I connect a notebook front end to the kernel-gateway server?
```
jupyter notebook --gateway-url=http://<gateway-server>:<gateway-port>
```
if you need additional configuration items, you can issue `jupyter notebook --help-all` and look at the `GatewayClient`-prefixed options.

**Comment by crossvalidator** [comment]
Thank you. I am able to  interrupt kernel and restart kernel using notebook frontend and the `kernel-gateway` on 2.5.0 version. 

This indicates some issue with my custom client. Will investigate the notebook codebase for this. 

Closing this issue. Thank you for your help!
