### ISSUE TITLE
block kwarg removed in jupyter-client 7

### ISSUE THREAD

**Issue by tschaume** [jupyter/kernel_gateway#367]
[This commit](https://github.com/jupyter/jupyter_client/commit/f365a22a22591c3bae04723b804585fe11934ce5) in jupyter-client 7 removes the `block` kwarg for `get_msg` used [here](https://github.com/jupyter/kernel_gateway/blob/213a8179c5a6e81a301cafc467549ef90855468f/kernel_gateway/services/kernels/manager.py#L104)

**Comment by kevin-bates** [comment]
hi @tschaume.  Did you want to provide a PR for this?  I believe it's a matter of using the channel helper methods instead as referenced in the resolution for issue 2 here: https://github.com/jupyter/jupyter_client/issues/640#issue-856223866

**Comment by tschaume** [comment]
@kevin-bates Thanks for the pointer! I started PR #368
