### ISSUE TITLE
How do I run some bootstrap code in the kernels before the startup files?

### ISSUE THREAD

**Issue by NightMachinary** [jupyter/kernel_gateway#370]
I like to run `some_flag = 1` before the `IJulia` kernel loads Julia's `startup.jl` file. Or before the Python kernel loads `~/.ipython/profile_default/startup/`. 

This is because I need to change the startup behavior depending on if they are running from a normal Jupyter notebook or from the kernel gateway server.

**Comment by kevin-bates** [comment]
This is more of a question for each kernel although you might find the following somewhat helpful.

1. KernelGateway will inject into the kernel's environment the variable/value [`KERNEL_GATEWAY=1`](https://github.com/jupyter/kernel_gateway/blob/265b99bd48da85de8e3d954613bb906fff5ff6b1/kernel_gateway/services/kernels/manager.py#L125) such that a kernel should be able to interrogate that variable's existence.  (Basically, if it exists, it will have a value of `1`.)
2. Take a look at [_Kernel Provisioning_](https://jupyter-client.readthedocs.io/en/latest/provisioning.html), recently introduced in jupyter_client. This introduces a framework that essentially abstracts the Popen portion of kernel management, thereby allowing for custom kernel provisioners to _provision_ the environment in which the kernel is running, yet still be managed by the Kernel Manager and hosting application. I suspect your provisioner could adjust configs prior to launching the kernel - assuming the kernel is always local.  However, I think this will ultimately boil down to where exactly you want to make adjustments.  If in the kernel process itself, then you're probably looking at having to alter each kernel to introduce this capability.

**Comment by NightMachinary** [comment]
Thanks, I think this will suffice for my use cases!
