### ISSUE TITLE
Travis stalls after tests succeed

### ISSUE THREAD

**Issue by parente** [jupyter/kernel_gateway#94]
See travis-ci/travis-ci#5555

**Comment by parente** [comment]
Hangs still happen, even after accounting for recent timeout problems in jupyter_client 4.2.x.

e.g., https://travis-ci.org/jupyter-incubator/kernel_gateway/jobs/113997896

I can reproduce the hang at the end of the test run reliable reliably on OSX outside our docker dev environment. Using dtruss on my mac, I see the following pattern repeated endlessly after nose logs test completion on stderr:

```
kevent(0x13, 0x0, 0x0)           = 0 0
socket(0x2, 0x1, 0x6)            = 6 0
fcntl(0x6, 0x2, 0x1)             = 0 0
fcntl(0x6, 0x3, 0x0)             = 2 0
fcntl(0x6, 0x4, 0x6)             = 0 0
connect(0x6, 0x101B637E8, 0x10)          = -1 Err#36
kevent(0x13, 0x700000101DD8, 0x1)                = 0 0
kevent(0x13, 0x0, 0x0)           = 1 0
kevent(0x13, 0x700000101E08, 0x1)                = 0 0
getsockopt(0x6, 0xFFFF, 0x1007)          = 0 0
close(0x6)               = 0 0
socket(0x2, 0x1, 0x6)            = 6 0
fcntl(0x6, 0x2, 0x1)             = 0 0
fcntl(0x6, 0x3, 0x0)             = 2 0
fcntl(0x6, 0x4, 0x6)             = 0 0
connect(0x6, 0x101C04278, 0x10)          = -1 Err#36
kevent(0x13, 0x700000101DD8, 0x1)                = 0 0
kevent(0x13, 0x0, 0x0)           = 1 0
kevent(0x13, 0x700000101E08, 0x1)                = 0 0
getsockopt(0x6, 0xFFFF, 0x1007)          = 0 0
close(0x6)               = 0 0
```

Still in some kind of loop requesting a socket perhaps? Maybe in a thread that prevents the main one from exiting?

(FWIW, errno 36 is EINPROGRESS.)

**Comment by willingc** [comment]
Leaving this as a reminder to self to check this error.

https://travis-ci.org/jupyter-incubator/kernel_gateway/jobs/114115936

<img width="916" alt="screen shot 2016-03-06 at 2 05 16 pm" src="https://cloud.githubusercontent.com/assets/2680980/13557414/a4cc4afc-e3a4-11e5-88ba-0a016ae1a321.png">

**Comment by parente** [comment]
@willingc that exception is in https://github.com/jupyter/kernel_gateway/issues/85 and rarer than the hang.

**Comment by parente** [comment]
@minrk I'm thinking the dtruss trace above is either some tornado or zeromq component doing something endlessly on the ioloop. I don't know why this would cause the process to hang if we stop the loop. But to be certain, is there some function we can use to clear out everything registered on the zmq provided ioloop?

Alternatively, does pyzmq / zmq do anything on a thread that could be stuck running and failing to join at the end of our tests sometimes?

**Comment by parente** [comment]
I put a `teardown` function into the tests package __init__.py to log some information and try to force a shutdown of the ioloop.

```python
import sys

from zmq.eventloop import ioloop
import threading

def teardown():
    print('stopping ioloop')
    ioloop.IOLoop.instance().stop()
    print(list(threading.enumerate()))
```

The hang still happens. When it does, only the main thread is in the list of running threads. Yet something is still ticking away according to dtruss trying to do a socket connect endlessly.

zmq thread outside of Python?

**Comment by parente** [comment]
May have hit on success with:

```python
from tornado import ioloop

def teardown():
    ioloop.IOLoop.current().stop()
    ioloop.IOLoop.current().close(True)
```

I've got the test suite running in an infinite loop on my mac where I hit the hang. If it continues unabated for 30 minutes or so, I'll try a PR and see what Travis does.

**Comment by willingc** [comment]
@parente Nice sleuthing.
